import { FormEvent, useEffect, useMemo, useState } from 'react';
import './accessibility-reviews.css';

const criteria = [
  { id: 'keyboard-operation', label: 'Keyboard operation', question: 'Can every required action be completed without a pointer?' },
  { id: 'focus-order-visible', label: 'Focus order and visibility', question: 'Does focus move logically and remain visibly identifiable?' },
  { id: 'screen-reader-semantics', label: 'Screen-reader semantics', question: 'Are names, roles, states, order, headings and announcements meaningful?' },
  { id: 'contrast-noncolor', label: 'Contrast and non-colour meaning', question: 'Is information perceivable without relying on colour alone?' },
  { id: 'zoom-reflow', label: 'Zoom and reflow', question: 'Does content remain operable and readable when enlarged or narrowed?' },
  { id: 'reduced-motion', label: 'Reduced motion', question: 'Does reduced-motion preference remove nonessential movement without hiding information?' },
  { id: 'error-recovery', label: 'Error recovery', question: 'Are errors visible, understandable, attributable and recoverable without repeated writes?' },
  { id: 'reading-demand', label: 'Reading demand', question: 'Is language explicit, age-respectful and proportionate to the actual task?' },
] as const;
const outcomes = ['met', 'failed', 'not-observed', 'not-applicable'];
const decisions = ['changes-required', 'deferred', 'observed-usable'];
type CriterionDraft = { outcome: string; evidence: string };
type Review = { id: string; surfaceId: string; reviewerIdentity: string; decision: string; runtimeEnvironment: string; inputAndAssistiveTechnology: string; viewportAndZoom: string; unresolvedFailures: string; reviewedUtc: string; criterionCount: number; failedCount: number; notObservedCount: number };
function blankCriteria(): Record<string, CriterionDraft> { return Object.fromEntries(criteria.map(value => [value.id, { outcome: '', evidence: '' }])); }
async function readJson<T>(endpoint: string, options?: RequestInit): Promise<T> { const response = await fetch(endpoint, options); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.state || `HTTP ${response.status}`); return payload as T; }

export function AccessibilityReviewPanel() {
  const [reviews, setReviews] = useState<Review[]>([]); const [reviewId, setReviewId] = useState(''); const [surfaceId, setSurfaceId] = useState('');
  const [reviewer, setReviewer] = useState(''); const [decision, setDecision] = useState('changes-required'); const [environment, setEnvironment] = useState('');
  const [inputTechnology, setInputTechnology] = useState(''); const [viewport, setViewport] = useState(''); const [unresolved, setUnresolved] = useState('');
  const [criterionDrafts, setCriterionDrafts] = useState<Record<string, CriterionDraft>>(blankCriteria); const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false); const [state, setState] = useState('Loading accessibility review evidence...');
  async function refresh() { setConfirmed(false); try { const data = await readJson<{ reviews: Review[] }>('/api/accessibility/reviews'); setReviews(data.reviews ?? []); setState('Current accessibility review evidence loaded. Reconfirm after reviewing this exact observation record.'); } catch (error) { setState(error instanceof Error ? error.message : 'Accessibility reviews could not be loaded.'); } }
  useEffect(() => { void refresh(); }, []);
  const complete = useMemo(() => criteria.every(value => criterionDrafts[value.id]?.outcome && criterionDrafts[value.id]?.evidence.trim().length >= 5), [criterionDrafts]);
  function updateField(setter: (value: string) => void, value: string) { setConfirmed(false); setter(value); }
  function updateCriterion(id: string, patch: Partial<CriterionDraft>) { setConfirmed(false); setCriterionDrafts(current => ({ ...current, [id]: { ...current[id], ...patch } })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) { setState('Confirm the single-surface observation boundary before writing.'); return; } setBusy(true); try {
    const result = await readJson<{ state: string }>('/api/accessibility/reviews', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': 'record-accessibility-review' }, body: JSON.stringify({ reviewId, surfaceId, reviewerIdentity: reviewer, decision, runtimeEnvironment: environment, inputAndAssistiveTechnology: inputTechnology, viewportAndZoom: viewport, unresolvedFailures: unresolved, criteria: criteria.map(value => ({ criterionId: value.id, outcome: criterionDrafts[value.id].outcome, evidence: criterionDrafts[value.id].evidence })) }) });
    setState(result.state); setConfirmed(false); await refresh();
  } catch (error) { setState(error instanceof Error ? error.message : 'Accessibility review write failed.'); } finally { setBusy(false); } }
  return <section id="workspace-accessibility-reviews" className="accessibility-reviews" aria-labelledby="accessibility-reviews-title"><header><div><p>HUMAN ACCESSIBILITY EVIDENCE · IMMUTABLE</p><h2 id="accessibility-reviews-title">Record what was observed, including what failed.</h2><span>One receipt covers one named surface in one stated environment. It never certifies the whole product.</span></div><button type="button" onClick={() => void refresh()} disabled={busy}>Refresh</button></header>
    <div className="accessibility-review-boundary"><strong>Observation is not certification.</strong><span>Identity, assistive technology and environment are recorded claims. A later environment or product revision needs a new review.</span></div>
    <form onSubmit={submit}><div className="accessibility-review-fields"><label>Stable review ID<input required pattern="[a-z0-9_-]{3,96}" value={reviewId} onChange={event => updateField(setReviewId, event.target.value)} /></label><label>Surface ID<input required pattern="[a-z0-9_-]{3,96}" value={surfaceId} onChange={event => updateField(setSurfaceId, event.target.value)} placeholder="workspace-learning-checks" /></label><label>Reviewer identity claim<input required minLength={2} maxLength={120} value={reviewer} onChange={event => updateField(setReviewer, event.target.value)} /></label><label>Decision<select value={decision} onChange={event => updateField(setDecision, event.target.value)}>{decisions.map(value => <option key={value}>{value}</option>)}</select></label></div>
      <label>Exact runtime environment<textarea required minLength={5} maxLength={2000} rows={3} value={environment} onChange={event => updateField(setEnvironment, event.target.value)} placeholder="Build/source identity, operating system, browser or WebView, display and observation boundary" /></label><label>Input and assistive technology used<textarea required minLength={4} maxLength={2000} rows={2} value={inputTechnology} onChange={event => updateField(setInputTechnology, event.target.value)} placeholder="Keyboard, pointer, touch, screen reader and versions actually exercised; use none-observed truthfully" /></label><label>Viewport, zoom and text scaling<textarea required minLength={4} maxLength={1000} rows={2} value={viewport} onChange={event => updateField(setViewport, event.target.value)} /></label><label>Unresolved failures<textarea required minLength={4} maxLength={4000} rows={3} value={unresolved} onChange={event => updateField(setUnresolved, event.target.value)} placeholder="Use exactly none only when no unresolved failure remains for this observation" /></label>
      <div className="accessibility-criterion-grid">{criteria.map(criterion => <article key={criterion.id}><header><code>{criterion.id}</code><strong>{criterion.label}</strong></header><p>{criterion.question}</p><label>Outcome<select required value={criterionDrafts[criterion.id].outcome} onChange={event => updateCriterion(criterion.id, { outcome: event.target.value })}><option value="">Select outcome</option>{outcomes.map(value => <option key={value}>{value}</option>)}</select></label><label>Observed evidence or non-applicability reason<textarea required minLength={5} maxLength={4000} rows={3} value={criterionDrafts[criterion.id].evidence} onChange={event => updateCriterion(criterion.id, { evidence: event.target.value })} /></label></article>)}</div>
      <label className="accessibility-review-confirm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I am recording one bounded human observation. This does not certify another surface, environment, revision, learner, installer, or the product as a whole.</label><button disabled={busy || !confirmed || !complete}>Record immutable accessibility review</button></form>
    <div className="accessibility-review-ledger"><h3>Accessibility review ledger</h3>{reviews.length === 0 ? <p>No accessibility reviews recorded.</p> : reviews.map(value => <article key={value.id} data-decision={value.decision}><header><strong>{value.surfaceId}</strong><em>{value.decision}</em></header><p>{value.id} · {value.reviewerIdentity} · {value.reviewedUtc}</p><footer><span>{value.criterionCount} criteria</span><span>{value.failedCount} failed</span><span>{value.notObservedCount} not observed</span><span>Unresolved: {value.unresolvedFailures}</span></footer></article>)}</div><output>{state}</output></section>;
}
