import { FormEvent, useEffect, useState } from 'react';
import './data-stewardship.css';

type Inventory = { id: string; label: string; purpose: string; tablePresent: boolean; recordCount: number; oldestUtc?: string; newestUtc?: string };
type Policy = { id: string; recordedBy: string; nextReviewDate: string; learnerRecordDays: number; attemptRecordDays: number; sessionReceiptDays: number; backupDays: number; rationale: string; deletionAuthority: string; recordedUtc: string };
async function readJson<T>(endpoint: string, options?: RequestInit): Promise<T> { const response = await fetch(endpoint, options); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.state || `HTTP ${response.status}`); return payload as T; }

export function DataStewardshipPanel() {
  const [inventory, setInventory] = useState<Inventory[]>([]); const [policies, setPolicies] = useState<Policy[]>([]);
  const [policyId, setPolicyId] = useState(''); const [recordedBy, setRecordedBy] = useState(''); const [reviewDate, setReviewDate] = useState('');
  const [learnerDays, setLearnerDays] = useState(365); const [attemptDays, setAttemptDays] = useState(365); const [sessionDays, setSessionDays] = useState(365); const [backupDays, setBackupDays] = useState(365);
  const [rationale, setRationale] = useState(''); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [state, setState] = useState('Loading local data inventory...');
  async function refresh() { setConfirmed(false); try { const data = await readJson<{ inventory: Inventory[]; policies: Policy[] }>('/api/storage/stewardship'); setInventory(data.inventory ?? []); setPolicies(data.policies ?? []); setState('Local data inventory and policy evidence loaded. Reconfirm after reviewing the exact proposed policy.'); } catch (error) { setState(error instanceof Error ? error.message : 'Data stewardship evidence could not be loaded.'); } }
  useEffect(() => { void refresh(); }, []);
  function updateText(setter: (value: string) => void, value: string) { setConfirmed(false); setter(value); }
  function updateDays(setter: (value: number) => void, value: number) { setConfirmed(false); setter(value); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) { setState('Confirm that policy recording performs no automatic deletion.'); return; } setBusy(true); try {
    const result = await readJson<{ state: string }>('/api/storage/stewardship', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': 'record-local-retention-policy' }, body: JSON.stringify({ policyId, recordedBy, nextReviewDate: reviewDate, learnerRecordDays: learnerDays, attemptRecordDays: attemptDays, sessionReceiptDays: sessionDays, backupDays, rationale, acknowledgesNoAutomaticDeletion: true }) });
    setState(result.state); setConfirmed(false); await refresh();
  } catch (error) { setState(error instanceof Error ? error.message : 'Retention-policy write failed.'); } finally { setBusy(false); } }
  const current = policies.at(-1);
  return <section id="workspace-data-stewardship" className="data-stewardship" aria-labelledby="data-stewardship-title"><header><div><p>LOCAL DATA STEWARDSHIP · HUMAN AUTHORITY</p><h2 id="data-stewardship-title">See what exists. Record policy. Delete nothing automatically.</h2><span>Counts and timestamps support review; they are not legal advice, consent evidence or deletion authority.</span></div><button type="button" onClick={() => void refresh()} disabled={busy}>Refresh</button></header>
    <div className="data-stewardship-warning"><strong>Database and backups are separate scopes.</strong><span>Removing a future live record would not remove it from an existing snapshot. Restore, export, withdrawal and deletion remain unavailable.</span></div>
    <div className="data-inventory"><h3>Current database inventory</h3>{inventory.map(value => <article key={value.id}><header><strong>{value.label}</strong><b>{value.recordCount}</b></header><p>{value.purpose}</p><footer><span>{value.tablePresent ? 'TABLE PRESENT' : 'NOT INITIALIZED'}</span><span>Oldest: {value.oldestUtc ?? 'none'}</span><span>Newest: {value.newestUtc ?? 'none'}</span></footer></article>)}</div>
    {current && <div className="current-retention-policy"><h3>Current recorded policy</h3><strong>{current.id}</strong><span>Recorded by {current.recordedBy} · review {current.nextReviewDate}</span><div><b>Learner {current.learnerRecordDays}d</b><b>Attempts {current.attemptRecordDays}d</b><b>Sessions {current.sessionReceiptDays}d</b><b>Backups {current.backupDays}d</b></div><p>{current.rationale}</p><code>{current.deletionAuthority}</code></div>}
    <form onSubmit={submit}><h3>Append retention-policy evidence</h3><div className="data-stewardship-fields"><label>Stable policy ID<input required pattern="[a-z0-9_-]{3,64}" value={policyId} onChange={event => updateText(setPolicyId, event.target.value)} /></label><label>Recorded by identity claim<input required minLength={2} maxLength={120} value={recordedBy} onChange={event => updateText(setRecordedBy, event.target.value)} /></label><label>Next human review date<input required type="date" value={reviewDate} onChange={event => updateText(setReviewDate, event.target.value)} /></label><label>Learner/profile days<input required type="number" min={1} max={3650} value={learnerDays} onChange={event => updateDays(setLearnerDays, Number(event.target.value))} /></label><label>Attempt/review days<input required type="number" min={1} max={3650} value={attemptDays} onChange={event => updateDays(setAttemptDays, Number(event.target.value))} /></label><label>Session-receipt days<input required type="number" min={1} max={3650} value={sessionDays} onChange={event => updateDays(setSessionDays, Number(event.target.value))} /></label><label>Backup days<input required type="number" min={1} max={3650} value={backupDays} onChange={event => updateDays(setBackupDays, Number(event.target.value))} /></label></div><label>Purpose, basis and review rationale<textarea required minLength={20} maxLength={4000} rows={4} value={rationale} onChange={event => updateText(setRationale, event.target.value)} placeholder="Why these planning windows are appropriate, who must review them and what evidence remains missing" /></label><label className="data-stewardship-confirm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I understand this appends policy evidence only. It performs no deletion, archival, export, consent withdrawal or legal-compliance decision.</label><button disabled={busy || !confirmed}>Record immutable policy</button></form>
    <div className="retention-policy-ledger"><h3>Policy history</h3>{policies.length === 0 ? <p>No retention policy recorded.</p> : policies.map(value => <article key={value.id}><header><strong>{value.id}</strong><span>{value.recordedUtc}</span></header><p>{value.rationale}</p><footer><span>Review {value.nextReviewDate}</span><span>{value.deletionAuthority}</span></footer></article>)}</div><output>{state}</output></section>;
}
