import { FormEvent, useEffect, useRef, useState } from 'react';
import './database-backups.css';

type Backup = { id: string; createdUtc: string; fileName: string; bytes: number; sha256: string; state: string; lastVerifiedUtc?: string; verificationState: string; error?: string; filePresent: boolean; observedBytes: number; presenceState: string };
type Overview = { ok: boolean; backupRoot: string; maximumBackups: number; snapshotMethod: string; receiptIncludedInSnapshot: boolean; verificationScope: string; backups: Backup[]; presentFiles: number; observedDatabaseFiles: number; capacityReached: boolean; orphanFiles: string[]; orphanScanTruncated: boolean; boundaries: string[] };
const defaultId = () => `backup-${new Date().toISOString().replace(/[^0-9]/g, '').slice(0, 14)}`;

export function DatabaseBackupPanel() {
  const [overview, setOverview] = useState<Overview | null>(null); const [id, setId] = useState(defaultId); const [state, setState] = useState('Loading local backup inventory...');
  const [busy, setBusy] = useState(true); const operationActive = useRef(false);
  async function refresh() { try { const response = await fetch('/api/storage/backups'); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); setOverview(payload); setState('Local backup inventory loaded'); } catch (error) { setState(`Backup inventory unavailable: ${error instanceof Error ? error.message : 'unknown error'}`); } }
  useEffect(() => { void refresh().finally(() => setBusy(false)); }, []);
  async function mutate(path: string, intent: string, body: object) { const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': intent }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || result.state || `HTTP ${response.status}`); return result; }
  async function create(event: FormEvent) { event.preventDefault(); if (operationActive.current) return; operationActive.current = true; setBusy(true); setState('Creating consistent local snapshot...'); try { const result = await mutate('/api/storage/backups', 'create-local-database-backup', { id }); setState(`Backup ${result.state}: ${result.fileName}`); setId(defaultId()); await refresh(); } catch (error) { setState(`Backup refused: ${error instanceof Error ? error.message : 'unknown error'}`); } finally { operationActive.current = false; setBusy(false); } }
  async function verify(backupId: string) { if (operationActive.current) return; operationActive.current = true; setBusy(true); setState(`Verifying ${backupId}...`); try { const result = await mutate('/api/storage/backups/verify', 'verify-local-database-backup', { id: backupId }); setState(`Backup ${result.state}: ${backupId}`); await refresh(); } catch (error) { setState(`Verification failed: ${error instanceof Error ? error.message : 'unknown error'}`); await refresh(); } finally { operationActive.current = false; setBusy(false); } }
  return <section id="workspace-backups" className="backup-shell" aria-labelledby="backup-title"><header><div><p>LOCAL EVIDENCE SAFETY</p><h2 id="backup-title">Make a consistent snapshot before the next risky step.</h2></div><span>{overview?.observedDatabaseFiles ?? 0} / {overview?.maximumBackups ?? 50} physical files · {overview?.presentFiles ?? 0} receipted present</span></header>
    <div className="backup-boundary"><strong>Single-root only.</strong> Snapshots stay under <code>{overview?.backupRoot ?? 'data/backups'}</code>. MA-Teacher will not auto-delete, restore, upload or sync them.</div>
    <div className="backup-boundary"><strong>Exact evidence boundary.</strong> Method: <code>{overview?.snapshotMethod ?? 'loading'}</code>. Creation receipt included inside snapshot: <code>{overview ? String(overview.receiptIncludedInSnapshot) : 'loading'}</code>. Verification: <code>{overview?.verificationScope ?? 'loading'}</code>; it does not prove logical SQLite integrity, restore, or restart survival.</div>
    {overview && (overview.orphanFiles.length > 0 || overview.orphanScanTruncated) && <div className="backup-boundary"><strong>Unreceipted backup files require human review.</strong> {overview.orphanFiles.length > 0 ? <span>Observed: {overview.orphanFiles.map(value => <code key={value}>{value}</code>)}</span> : <span>No orphan appeared within the bounded filename sample.</span>} {overview.orphanScanTruncated && <span>The physical-file scan reached its bound; additional orphan state is unknown.</span>} No file was deleted, adopted, opened, or trusted.</div>}
    <form onSubmit={create}><label>Stable backup ID<input value={id} onChange={event => setId(event.target.value)} disabled={busy} required /></label><button disabled={busy || !id.trim()}>Create database snapshot</button><output>{state}</output></form>
    <div className="backup-ledger">{overview?.backups.length ? overview.backups.map(value => <article key={value.id}><header><div><strong>{value.id}</strong><span>{value.fileName}</span></div><em>{value.verificationState}</em></header><dl><dt>Created</dt><dd>{new Date(value.createdUtc).toLocaleString()}</dd><dt>Size</dt><dd>{value.bytes.toLocaleString()} bytes · {value.presenceState}</dd><dt>SHA-256</dt><dd><code>{value.sha256 || 'not recorded'}</code></dd>{value.lastVerifiedUtc && <><dt>Byte identity checked</dt><dd>{new Date(value.lastVerifiedUtc).toLocaleString()}</dd></>}{value.error && <><dt>Error</dt><dd>{value.error}</dd></>}</dl><button onClick={() => void verify(value.id)} disabled={busy || value.state !== 'created'}>Recompute SHA-256 byte identity</button></article>) : <p>No backup receipts yet.</p>}</div>
  </section>;
}
