import { useEffect, useMemo, useState } from 'react';
import './learning-progress.css';

type Summary = { learnerId: string; learnerDisplayName: string; subject: string; learningStage: string; attempts: number; unreviewed: number; met: number; partiallyMet: number; notYet: number; invalid: number; lastSubmittedUtc?: string };
type Entry = { attemptId: string; checkId: string; lessonId: string; lessonTitle: string; subject: string; learningStage: string; learnerId: string; learnerDisplayName: string; prompt: string; successCriteria: string; responseText: string; submittedUtc: string; reviewState: string; outcome?: string; feedback?: string; reviewedUtc?: string; evidenceCount: number; evidenceNeed: string };
type Overview = { ok: boolean; interpretationState: string; summaries: Summary[]; entries: Entry[]; boundaries: string[] };

export function LearningProgressPanel() {
  const [overview, setOverview] = useState<Overview | null>(null); const [learner, setLearner] = useState('all'); const [subject, setSubject] = useState('all'); const [state, setState] = useState('Loading evidence ledger...');
  async function refresh() { try { const response = await fetch('/api/learning/progress'); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || `HTTP ${response.status}`); setOverview(payload); setState('Exact local attempt evidence loaded'); } catch (error) { setState(`Progress evidence unavailable: ${error instanceof Error ? error.message : 'unknown error'}`); } }
  useEffect(() => { void refresh(); }, []);
  const learners = useMemo(() => ['all', ...Array.from(new Set((overview?.summaries ?? []).map(value => value.learnerId)))], [overview]);
  const subjects = useMemo(() => ['all', ...Array.from(new Set((overview?.summaries ?? []).filter(value => learner === 'all' || value.learnerId === learner).map(value => value.subject)))], [overview, learner]);
  const summaries = (overview?.summaries ?? []).filter(value => (learner === 'all' || value.learnerId === learner) && (subject === 'all' || value.subject === subject));
  const entries = (overview?.entries ?? []).filter(value => (learner === 'all' || value.learnerId === learner) && (subject === 'all' || value.subject === subject));
  return <section id="workspace-progress" className="progress-shell" aria-labelledby="progress-title"><header><div><p>PROGRESS EVIDENCE · NO SCORE</p><h2 id="progress-title">See what happened. Do not invent what it means.</h2></div><button onClick={() => void refresh()}>Refresh ledger</button></header>
    <div className="progress-boundary"><strong>{overview?.interpretationState ?? 'unavailable'}</strong> Attempt counts are not grades, percentages, ability levels, rankings or mastery estimates.</div>
    <div className="progress-filters"><label>Learner<select value={learner} onChange={event => { setLearner(event.target.value); setSubject('all'); }}>{learners.map(value => <option key={value} value={value}>{value === 'all' ? 'All learners' : overview?.summaries.find(item => item.learnerId === value)?.learnerDisplayName}</option>)}</select></label><label>Subject<select value={subject} onChange={event => setSubject(event.target.value)}>{subjects.map(value => <option key={value}>{value === 'all' ? 'All subjects' : value}</option>)}</select></label><output>{state}</output></div>
    <div className="progress-summary-grid">{summaries.map(value => <article key={`${value.learnerId}-${value.subject}-${value.learningStage}`}><header><strong>{value.learnerDisplayName}</strong><span>{value.subject} · {value.learningStage}</span></header><div><span><b>{value.attempts}</b>attempts</span><span><b>{value.unreviewed}</b>unreviewed</span><span><b>{value.met}</b>met</span><span><b>{value.partiallyMet}</b>partial</span><span><b>{value.notYet}</b>not yet</span><span><b>{value.invalid}</b>invalid</span></div><footer>{value.lastSubmittedUtc ? `Last response ${new Date(value.lastSubmittedUtc).toLocaleString()}` : 'No response evidence'}</footer></article>)}</div>
    <div className="progress-ledger"><h3>Inspectable attempt ledger</h3>{entries.length === 0 ? <p>No matching attempts.</p> : entries.map(value => <article key={value.attemptId}><header><div><strong>{value.learnerDisplayName} · {value.subject}</strong><span>{value.lessonTitle} · {value.learningStage}</span></div><em>{value.reviewState}{value.outcome ? ` · ${value.outcome}` : ''}</em></header><dl><dt>Prompt</dt><dd>{value.prompt}</dd><dt>Criteria</dt><dd>{value.successCriteria}</dd><dt>Response</dt><dd>{value.responseText}</dd>{value.feedback && <><dt>Feedback</dt><dd>{value.feedback}</dd></>}</dl><footer><span>{value.evidenceCount} curriculum link{value.evidenceCount === 1 ? '' : 's'}</span><strong>{value.evidenceNeed}</strong></footer></article>)}</div>
  </section>;
}
