import { FormEvent, useEffect, useState } from 'react';
import './learning-checks.css';

type Draft = { id: string; title: string };
type LessonEvidence = { id: string; subject: string; learningStage: string; statementText: string };
type LessonDetail = { ok: boolean; lesson: { id: string; learnerId: string; learnerDisplayName: string }; evidence: LessonEvidence[] };
type Check = { id: string; lessonId: string; lessonTitle: string; learnerId: string; learnerDisplayName: string; prompt: string; successCriteria: string; evidenceState: string; status: string; lessonFingerprint?: string; fingerprintCurrent: boolean; currencyState: string; evidenceCount: number };
type Attempt = { id: string; checkId: string; learnerId: string; learnerDisplayName: string; responseText: string; reviewState: string; outcome?: string; feedback?: string; attachmentName?: string; attachmentMediaType?: string; attachmentBytes?: number; attachmentSha256?: string };
type WorkspacePayload = { ok: boolean; error?: string; lessonDrafts?: Draft[] };
type CheckPayload = { ok: boolean; error?: string; checks?: Check[]; attempts?: Attempt[] };
type MutationPayload = { ok: boolean; error?: string; state?: string };

async function readLearningCheckJson<T>(response: Response, label: string): Promise<T> {
  const body = await response.text();
  if (!body.trim()) throw new Error(`${label} returned no data.`);
  try { return JSON.parse(body) as T; }
  catch { throw new Error(`${label} returned a reply this screen could not read.`); }
}

export function LearningCheckPanel({ mode = 'teacher' }: { mode?: 'learner' | 'teacher' }) {
  const isTeacher = mode === 'teacher';
  const [drafts, setDrafts] = useState<Draft[]>([]); const [lessonId, setLessonId] = useState(''); const [detail, setDetail] = useState<LessonDetail | null>(null);
  const [checks, setChecks] = useState<Check[]>([]); const [attempts, setAttempts] = useState<Attempt[]>([]); const [selectedEvidence, setSelectedEvidence] = useState<string[]>([]);
  const [checkId, setCheckId] = useState(''); const [prompt, setPrompt] = useState(''); const [criteria, setCriteria] = useState('');
  const [attemptId, setAttemptId] = useState(''); const [attemptCheckId, setAttemptCheckId] = useState(''); const [response, setResponse] = useState('');
  const [workFile, setWorkFile] = useState<File | null>(null);
  const [reviewAttemptId, setReviewAttemptId] = useState(''); const [outcome, setOutcome] = useState('not-yet'); const [feedback, setFeedback] = useState(''); const [state, setState] = useState('Not loaded');

  async function refresh() {
    try {
      const [workspaceResponse, checksResponse] = await Promise.all([fetch('/api/teaching/workspace'), fetch('/api/teaching/checks')]);
      const [workspace, checkData] = await Promise.all([readLearningCheckJson<WorkspacePayload>(workspaceResponse, 'Learning workspace'), readLearningCheckJson<CheckPayload>(checksResponse, 'Learning checks')]);
      if (!workspaceResponse.ok || !workspace.ok || !checksResponse.ok || !checkData.ok) throw new Error('Learning-check workspace refused.');
      const nextDrafts = Array.isArray(workspace.lessonDrafts) ? workspace.lessonDrafts : []; const nextChecks = Array.isArray(checkData.checks) ? checkData.checks : []; const nextAttempts = Array.isArray(checkData.attempts) ? checkData.attempts : [];
      setDrafts(nextDrafts); setChecks(nextChecks); setAttempts(nextAttempts); setLessonId(current => current && nextDrafts.some((item: Draft) => item.id === current) ? current : nextDrafts[0]?.id || ''); setAttemptCheckId(current => current && nextChecks.some((item: Check) => item.id === current && item.fingerprintCurrent) ? current : nextChecks.find((item: Check) => item.fingerprintCurrent)?.id || ''); setReviewAttemptId(current => current && nextAttempts.some((item: Attempt) => item.id === current && item.reviewState === 'unreviewed') ? current : nextAttempts.find((item: Attempt) => item.reviewState === 'unreviewed')?.id || ''); setState(isTeacher ? 'Manual practice workspace loaded' : 'Your practice is ready.');
    } catch (error) { setState(isTeacher ? `Load failed: ${error instanceof Error ? error.message : 'unknown error'}` : 'We could not open practice. Ask your teacher to check the app.'); }
  }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => {
    let cancelled = false;
    if (!lessonId) { setDetail(null); return () => { cancelled = true; }; }
    void (async () => {
      try {
        const response = await fetch(`/api/teaching/lessons/${encodeURIComponent(lessonId)}`);
        const value = await readLearningCheckJson<LessonDetail>(response, 'Lesson details');
        if (!cancelled) { setDetail(response.ok && value.ok ? value : null); setSelectedEvidence([]); }
      } catch { if (!cancelled) { setDetail(null); setSelectedEvidence([]); } }
    })();
    return () => { cancelled = true; };
  }, [lessonId]);

  async function post(path: string, intent: string, body: object) {
    const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': intent }, body: JSON.stringify(body) });
    const result = await readLearningCheckJson<MutationPayload>(response, 'Learning-check action'); if (!response.ok || !result.ok) throw new Error(result.error || result.state || `HTTP ${response.status}`); return result;
  }
  async function createCheck(event: FormEvent) { event.preventDefault(); try { const result = await post('/api/teaching/checks', 'create-evidence-linked-check', { id: checkId, lessonId, prompt, successCriteria: criteria, curriculumCandidateIds: selectedEvidence }); setState(`Check: ${result.state}`); await refresh(); } catch (error) { setState(`Check refused: ${error instanceof Error ? error.message : 'unknown error'}`); } }
  async function submitAttempt(event: FormEvent) { event.preventDefault(); const check = checks.find(value => value.id === attemptCheckId); if (!check) return; try { if (workFile && workFile.size > 10 * 1024 * 1024) throw new Error('Work attachment exceeds the 10 MB boundary.'); let attachmentBase64: string | null = null; if (workFile) { const bytes = new Uint8Array(await workFile.arrayBuffer()); let binary = ''; for (let offset = 0; offset < bytes.length; offset += 32768) binary += String.fromCharCode(...bytes.subarray(offset, offset + 32768)); attachmentBase64 = btoa(binary); } const submissionId = isTeacher ? attemptId : `work-${window.crypto.randomUUID()}`; const result = await post('/api/teaching/check-attempts', 'submit-learning-check-attempt', { id: submissionId, checkId: attemptCheckId, learnerId: check.learnerId, responseText: response, attachmentName: workFile?.name ?? null, attachmentMediaType: workFile?.type ?? null, attachmentBase64 }); setState(isTeacher ? `Attempt: ${result.state}` : 'Your work was sent for a person to review.'); setAttemptId(''); setResponse(''); setWorkFile(null); await refresh(); } catch (error) { setState(isTeacher ? `Attempt refused: ${error instanceof Error ? error.message : 'unknown error'}` : 'We could not send your work. Ask your teacher to check it.'); } }
  async function reviewAttempt(event: FormEvent) { event.preventDefault(); try { const result = await post('/api/teaching/check-reviews', 'review-learning-check-attempt', { attemptId: reviewAttemptId, outcome, feedback }); setState(`Review: ${result.state}`); await refresh(); } catch (error) { setState(`Review refused: ${error instanceof Error ? error.message : 'unknown error'}`); } }

  const selectedCheck = checks.find(value => value.id === attemptCheckId); const unreviewed = attempts.filter(value => value.reviewState === 'unreviewed');
  const currentChecks = checks.filter(value => value.fingerprintCurrent);
  const learnerAttempts = selectedCheck ? attempts.filter(value => value.checkId === selectedCheck.id && value.learnerId === selectedCheck.learnerId) : [];
  return <section id="workspace-learning-checks" className={`learning-check-shell${isTeacher ? '' : ' learning-check-shell--learner'}`} aria-labelledby="learning-check-title"><header><div><p>{isTeacher ? 'MANUAL PRACTICE LOOP' : 'YOUR PRACTICE'}</p><h2 id="learning-check-title">{isTeacher ? 'Ask. Answer. Review. Never fake the score.' : 'Show what you know. A person checks it.'}</h2></div><output role="status" aria-live="polite">{state}</output></header>
    <div className={`learning-check-columns${isTeacher ? '' : ' learning-check-columns--learner'}`}>
      {isTeacher && <form onSubmit={createCheck}><h3>1 · Author a check</h3><label>Lesson<select value={lessonId} onChange={event => setLessonId(event.target.value)}><option value="">Select lesson</option>{drafts.map(value => <option key={value.id} value={value.id}>{value.title}</option>)}</select></label><label>Stable check ID<input value={checkId} onChange={event => setCheckId(event.target.value)} required /></label><label>Prompt<textarea rows={4} value={prompt} onChange={event => setPrompt(event.target.value)} required /></label><label>Success criteria<textarea rows={4} value={criteria} onChange={event => setCriteria(event.target.value)} required /></label><fieldset><legend>Lesson evidence</legend>{detail?.evidence.map(value => <label className="check-evidence" key={value.id}><input type="checkbox" checked={selectedEvidence.includes(value.id)} onChange={event => setSelectedEvidence(current => event.target.checked ? [...current, value.id] : current.filter(id => id !== value.id))} /><span><strong>{value.subject} · {value.learningStage}</strong>{value.statementText}</span></label>)}</fieldset><button disabled={!lessonId || selectedEvidence.length === 0}>Save operator-authored check</button></form>}
      <form className="learner-work-form" onSubmit={submitAttempt}><h3>{isTeacher ? '2 · Submit work for marking' : 'Send in my work'}</h3><label>{isTeacher ? 'Current practice check' : 'Choose your question'}<select value={attemptCheckId} onChange={event => setAttemptCheckId(event.target.value)}><option value="">{isTeacher ? 'Select current check' : 'Choose a question'}</option>{(isTeacher ? checks : currentChecks).map(value => <option key={value.id} value={value.id} disabled={!value.fingerprintCurrent}>{isTeacher ? `${value.fingerprintCurrent ? 'CURRENT' : value.currencyState.toUpperCase()} · ${value.prompt.slice(0, 70)}` : value.prompt.slice(0, 90)}</option>)}</select></label>{selectedCheck && <div className="active-check"><strong>{selectedCheck.prompt}</strong><span>{isTeacher ? `For ${selectedCheck.learnerDisplayName} · ${selectedCheck.currencyState}` : `This question is for ${selectedCheck.learnerDisplayName}.`}</span><p>{isTeacher ? 'Reviewer criteria' : 'What good work may show'}: {selectedCheck.successCriteria}</p></div>}{!isTeacher && currentChecks.length === 0 ? <p className="learner-empty-check">Your teacher has not shared a practice question yet.</p> : null}{isTeacher && <label>Stable attempt ID<input value={attemptId} onChange={event => setAttemptId(event.target.value)} required /></label>}<label>{isTeacher ? 'Typed response (optional when a file is attached)' : 'Type your answer, or add a file below'}<textarea rows={isTeacher ? 8 : 6} value={response} onChange={event => setResponse(event.target.value)} /></label><label className="work-attachment">{isTeacher ? 'Attach work (optional)' : 'Add one file (optional)'}<input type="file" accept=".pdf,.txt,.rtf,.doc,.docx,.odt,.png,.jpg,.jpeg,.webp" onChange={event => setWorkFile(event.target.files?.[0] ?? null)} /><span>{workFile ? `${workFile.name} · ${(workFile.size / 1024).toFixed(1)} KB` : 'PDF, text, Word, ODT or picture · maximum 10 MB'}</span></label>{isTeacher ? <p className="work-marking-boundary">The original file is stored inside the local database with SHA-256 evidence. It is not sent to a model or marked automatically.</p> : <p className="work-marking-boundary">Your work stays on your teacher's computer. A person reviews it. A robot does not mark it.</p>}<button disabled={!selectedCheck?.fingerprintCurrent || (!response.trim() && !workFile)}>{isTeacher ? 'Submit unreviewed work' : 'Send my work for review'}</button></form>
      {isTeacher && <form onSubmit={reviewAttempt}><h3>3 · Human review</h3><label>Unreviewed attempt<select value={reviewAttemptId} onChange={event => setReviewAttemptId(event.target.value)}><option value="">Select attempt</option>{unreviewed.map(value => <option key={value.id} value={value.id}>{value.learnerDisplayName} · {value.id}</option>)}</select></label>{attempts.find(value => value.id === reviewAttemptId) && <blockquote>{attempts.find(value => value.id === reviewAttemptId)?.responseText || 'No typed response. Review the attached work.'}</blockquote>}{attempts.find(value => value.id === reviewAttemptId)?.attachmentName && <a className="work-download" href={`/api/teaching/check-attempts/${encodeURIComponent(reviewAttemptId)}/attachment`} download>{attempts.find(value => value.id === reviewAttemptId)?.attachmentName} · open original work</a>}<label>Outcome<select value={outcome} onChange={event => setOutcome(event.target.value)}><option value="met">met</option><option value="partially-met">partially met</option><option value="not-yet">not yet</option><option value="invalid">invalid attempt</option></select></label><label>Feedback<textarea rows={7} value={feedback} onChange={event => setFeedback(event.target.value)} required /></label><button disabled={!reviewAttemptId}>Record human review</button></form>}
      {!isTeacher && <aside className="learner-review-note"><h3>What happens next?</h3><ol><li>You send an answer or one file.</li><li>A person reads your work.</li><li>Your feedback appears in Progress.</li></ol>{selectedCheck && learnerAttempts.length > 0 ? <p><strong>{learnerAttempts.length}</strong> piece{learnerAttempts.length === 1 ? '' : 's'} of work sent for this question.</p> : <p>Your first piece of work will appear here after you send it.</p>}</aside>}
    </div>
    {isTeacher && <div className="check-currency-ledger"><h3>Practice-check currency</h3>{checks.length === 0 ? <p>No practice checks recorded.</p> : checks.map(value => <article key={value.id} data-currency={value.currencyState}><header><strong>{value.id}</strong><span>{value.currencyState.toUpperCase()}</span></header><p>{value.lessonTitle} · {value.prompt}</p><code>{value.lessonFingerprint ?? 'legacy row · no lesson fingerprint recorded'}</code></article>)}</div>}
    {isTeacher && <div className="attempt-ledger"><h3>Submitted work ledger</h3>{attempts.length === 0 ? <p>No work submitted.</p> : attempts.map(value => <article key={value.id}><header><strong>{value.learnerDisplayName}</strong><span>{value.id} · {value.reviewState}{value.outcome ? ` · ${value.outcome}` : ''}</span></header><p>{value.responseText || 'Attachment-only submission'}</p>{value.attachmentName && <div className="attempt-attachment"><a href={`/api/teaching/check-attempts/${encodeURIComponent(value.id)}/attachment`} download>{value.attachmentName}</a><span>{value.attachmentMediaType} · {((value.attachmentBytes ?? 0) / 1024).toFixed(1)} KB</span><code>SHA-256 {value.attachmentSha256}</code></div>}{value.feedback && <footer>{value.feedback}</footer>}</article>)}</div>}
  </section>;
}
