import { FormEvent, useEffect, useMemo, useState } from 'react';
import { lessonReviewCategories, type LessonReviewCriterion } from './lesson-review-criteria';
import { focusWorkspaceSurface } from './workspace-navigation';
import './lesson-review-records.css';

type Lesson = { id: string; title: string; subject: string; learningStage: string; status: string; currentFingerprint: string; latestDecision?: string; latestReviewCurrent: boolean; reviewCount: number };
type Review = { id: string; lessonId: string; lessonFingerprint: string; reviewerIdentity: string; decision: string; runtimeEnvironment: string; derivativeEvidence: string; unresolvedFailures: string; reviewedUtc: string; criterionCount: number; fingerprintCurrent: boolean };
type CriterionDraft = { outcome: string; evidence: string };
const decisions = ['approved-for-use', 'changes-required', 'deferred']; const outcomes = ['met', 'failed', 'not-applicable'];
const allCriteria: readonly LessonReviewCriterion[] = lessonReviewCategories.flatMap<LessonReviewCriterion>(category => [...category.criteria]);
function blankCriteria(): Record<string, CriterionDraft> { return Object.fromEntries(allCriteria.map(value => [value.id, { outcome: '', evidence: '' }])); }
async function readJson<T>(endpoint: string, options?: RequestInit): Promise<T> { const response = await fetch(endpoint, options); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.state || `HTTP ${response.status}`); return payload as T; }

export function LessonReviewRecordPanel() {
  const [lessons, setLessons] = useState<Lesson[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [lessonId, setLessonId] = useState('');
  const [reviewId, setReviewId] = useState(''); const [reviewer, setReviewer] = useState(''); const [decision, setDecision] = useState(decisions[1]);
  const [runtime, setRuntime] = useState(''); const [derivative, setDerivative] = useState('not-used'); const [unresolved, setUnresolved] = useState('');
  const [criteria, setCriteria] = useState<Record<string, CriterionDraft>>(blankCriteria); const [confirmed, setConfirmed] = useState(false);
  const [busy, setBusy] = useState(false); const [state, setState] = useState('Loading lesson review evidence...');
  async function refresh() { setConfirmed(false); try { const data = await readJson<{ lessons: Lesson[]; reviews: Review[] }>('/api/teaching/lesson-reviews'); setLessons(data.lessons ?? []); setReviews(data.reviews ?? []); setState('Current lesson review evidence loaded. Reconfirm after reviewing the exact saved fingerprint and evidence.'); } catch (error) { setState(error instanceof Error ? error.message : 'Lesson reviews could not be loaded.'); } }
  useEffect(() => { void refresh(); }, []);
  const selected = lessons.find(value => value.id === lessonId); const completeCriteria = useMemo(() => allCriteria.every(value => criteria[value.id]?.outcome && criteria[value.id]?.evidence.trim().length >= 5), [criteria]);
  function updateField(setter: (value: string) => void, value: string) { setConfirmed(false); setter(value); }
  function updateCriterion(id: string, patch: Partial<CriterionDraft>) { setConfirmed(false); setCriteria(current => ({ ...current, [id]: { ...current[id], ...patch } })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) { setState('Confirm the exact-review boundary before writing.'); return; } setBusy(true); try {
    const result = await readJson<{ state: string; lessonFingerprint: string }>('/api/teaching/lesson-reviews', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': 'record-exact-lesson-review' }, body: JSON.stringify({ reviewId, lessonId, reviewerIdentity: reviewer, decision, runtimeEnvironment: runtime, derivativeEvidence: derivative, unresolvedFailures: unresolved, criteria: allCriteria.map(value => ({ criterionId: value.id, outcome: criteria[value.id].outcome, evidence: criteria[value.id].evidence })) }) });
    setState(`${result.state} · ${result.lessonFingerprint}`); setConfirmed(false); await refresh();
  } catch (error) { setState(error instanceof Error ? error.message : 'Lesson review write failed.'); } finally { setBusy(false); } }
  return <section id="workspace-lesson-review-records" className="lesson-review-records" aria-labelledby="lesson-review-records-title"><header><div><p>EXACT LESSON REVIEW · IMMUTABLE EVIDENCE</p><h2 id="lesson-review-records-title">Review what was saved, not what you remember.</h2><span>Every criterion is required. Approval unlocks practice authoring but never edits or publishes the lesson.</span></div><button type="button" onClick={() => void refresh()} disabled={busy}>Refresh</button></header>
    <div className="lesson-review-record-boundary"><strong>Identity boundary</strong><span>The reviewer name is a recorded claim, not authentication or proof of qualification. Inspect the lesson in its actual delivery environment before relying on it.</span></div>
    <form onSubmit={submit}><div className="lesson-review-record-fields"><label>Lesson<select required value={lessonId} onChange={event => updateField(setLessonId, event.target.value)}><option value="">Select a saved lesson</option>{lessons.map(value => <option key={value.id} value={value.id}>{value.title} · {value.subject} · {value.learningStage}</option>)}</select></label><label>Stable review ID<input required pattern="[a-z0-9_-]{3,64}" value={reviewId} onChange={event => updateField(setReviewId, event.target.value)} /></label><label>Reviewer identity<input required maxLength={120} value={reviewer} onChange={event => updateField(setReviewer, event.target.value)} /></label><label>Decision<select value={decision} onChange={event => updateField(setDecision, event.target.value)}>{decisions.map(value => <option key={value}>{value}</option>)}</select></label></div>
      {selected && <div className="lesson-review-selected"><div><strong>{selected.title}</strong><span>{selected.id} · {selected.status}</span></div><code>{selected.currentFingerprint}</code><span>{selected.latestDecision ?? 'never reviewed'} · {selected.latestReviewCurrent ? 'current fingerprint' : 'no current review'}</span><button type="button" onClick={() => focusWorkspaceSurface('workspace-lesson-reader')}>Open lesson reader</button></div>}
      <label>Observed runtime and delivery environment<textarea required minLength={5} maxLength={2000} rows={3} value={runtime} onChange={event => updateField(setRuntime, event.target.value)} placeholder="Exact browser/view, viewport, input method and observation boundary" /></label><label>Print or derivative evidence<textarea required minLength={4} maxLength={2000} rows={2} value={derivative} onChange={event => updateField(setDerivative, event.target.value)} /></label><label>Unresolved failures<textarea required minLength={4} maxLength={4000} rows={3} value={unresolved} onChange={event => updateField(setUnresolved, event.target.value)} placeholder="Use exactly none only when no unresolved failure remains" /></label>
      <div className="lesson-review-record-criteria">{lessonReviewCategories.map(category => <article key={category.id}><header><strong>{category.label}</strong><span>{category.purpose}</span></header>{category.criteria.map(criterion => <section key={criterion.id}><div><code>{criterion.id}</code><b>{criterion.question}</b></div><label>Outcome<select required value={criteria[criterion.id].outcome} onChange={event => updateCriterion(criterion.id, { outcome: event.target.value })}><option value="">Select outcome</option>{outcomes.map(value => <option key={value}>{value}</option>)}</select></label><label>Observed evidence or non-applicability reason<textarea required minLength={5} maxLength={4000} rows={2} value={criteria[criterion.id].evidence} onChange={event => updateCriterion(criterion.id, { evidence: event.target.value })} /></label><p>Stop use when: {criterion.stopWhen}</p></section>)}</article>)}</div>
      <label className="lesson-review-record-confirm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I am recording a review of this exact saved lesson fingerprint. This does not edit or publish it.</label><button disabled={busy || !selected || !confirmed || !completeCriteria}>Record immutable lesson review</button></form>
    <div className="lesson-review-record-ledger"><h3>Review ledger</h3>{reviews.length === 0 ? <p>No lesson reviews recorded.</p> : reviews.map(value => <article key={value.id}><header><strong>{value.id}</strong><em>{value.decision}</em></header><p>{value.lessonId} · {value.reviewerIdentity} · {value.reviewedUtc}</p><code>{value.lessonFingerprint}</code><footer><span>{value.criterionCount} criteria</span><span>{value.fingerprintCurrent ? 'CURRENT FINGERPRINT' : 'STALE FINGERPRINT'}</span><span>Unresolved: {value.unresolvedFailures}</span></footer></article>)}</div><output>{state}</output></section>;
}
