import { feedbackPlanningEntries } from './feedback-planning-data';
import { questioningPlanningEntries } from './questioning-planning-data';
import { vocabularyEntries } from './vocabulary-planning-data';

export interface TeachingDataProvenanceEntry {
  id: string;
  title: string;
  sourcePath: string;
  boundaryPath: string;
  contentClass: 'Original planning data' | 'Navigation guidance' | 'Governed intake candidates' | 'Jurisdiction orientation' | 'Review checklist';
  declaredItems: string;
  author: string;
  crewActivity: string;
  crewResponse: string;
  externalAssistantUsed: false;
  externalAutomationUsed: false;
  evidenceStatus: 'Source present / not executed';
  authorityBoundary: string;
  nextEvidence: string;
}

export const teachingDataProvenanceEntries: TeachingDataProvenanceEntry[] = [
  {
    id: 'teaching-evidence-checklist',
    title: 'Teaching evidence checklist',
    sourcePath: 'web/src/TeachingEvidenceChecklistPanel.tsx',
    boundaryPath: 'docs/TEACHING_EVIDENCE_CHECKLIST_BOUNDARY.md',
    contentClass: 'Review checklist',
    declaredItems: '10 non-authoritative review prompts',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not a score, gate, certification, readiness result, lesson approval, accessibility proof or canonical receipt.',
    nextEvidence: 'Build, disclosure behavior, keyboard/screen-reader review, visual review and human acceptance remain separate.',
  },
  {
    id: 'jurisdiction-stage-guidance',
    title: 'Jurisdiction stage guidance',
    sourcePath: 'web/src/jurisdiction-stage-guidance.ts',
    boundaryPath: 'docs/JURISDICTION_STAGE_GUIDANCE_BOUNDARY.md',
    contentClass: 'Jurisdiction orientation',
    declaredItems: '4 unaccepted research guides',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not stage conversion, learner classification, curriculum acceptance, placement advice or lesson authority.',
    nextEvidence: 'Governed source review, subject/stage review, build, render, accessibility interaction and human acceptance remain separate.',
  },
  {
    id: 'curriculum-reference-candidates',
    title: 'Curriculum reference candidates',
    sourcePath: 'web/src/curriculum-reference-candidates.ts',
    boundaryPath: 'docs/CURRICULUM_REFERENCE_CANDIDATE_SURFACE.md',
    contentClass: 'Governed intake candidates',
    declaredItems: '15 official-source candidates',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not accepted teaching references, curriculum mappings, copied content, lesson authority or live source verification.',
    nextEvidence: 'Governed source retrieval, effective-date review, licensing, fingerprinting, human acceptance and database integration remain separate.',
  },
  {
    id: 'vocabulary-planning',
    title: 'Vocabulary planning',
    sourcePath: 'web/src/vocabulary-planning-data.ts',
    boundaryPath: 'docs/VOCABULARY_TEACHING_BOUNDARY.md',
    contentClass: 'Original planning data',
    declaredItems: `${vocabularyEntries.length} source entries`,
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not accepted curriculum, learner evidence, assessment, diagnosis or progression.',
    nextEvidence: 'Source review, subject review, build, render, accessibility interaction and human acceptance remain separate.',
  },
  {
    id: 'questioning-planning',
    title: 'Questioning planning',
    sourcePath: 'web/src/questioning-planning-data.ts',
    boundaryPath: 'docs/QUESTIONING_TEACHING_BOUNDARY.md',
    contentClass: 'Original planning data',
    declaredItems: `${questioningPlanningEntries.length} source entries`,
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not a learner-response rubric, diagnosis, score, progression rule or automated dialogue.',
    nextEvidence: 'Pedagogical review, subject review, build, render, adaptive-use observation and human acceptance remain separate.',
  },
  {
    id: 'feedback-planning',
    title: 'Descriptive feedback planning',
    sourcePath: 'web/src/feedback-planning-data.ts',
    boundaryPath: 'docs/FEEDBACK_TEACHING_BOUNDARY.md',
    contentClass: 'Original planning data',
    declaredItems: `${feedbackPlanningEntries.length} source entries`,
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not evidence about a real learner, a grade, praise score, diagnosis, profile or approval.',
    nextEvidence: 'Teaching review, subject review, build, render, accessibility interaction and human acceptance remain separate.',
  },
  {
    id: 'teaching-toolkit-path',
    title: 'Teaching toolkit path',
    sourcePath: 'web/src/TeachingToolkitPathPanel.tsx',
    boundaryPath: 'docs/TEACHING_TOOLKIT_PATH_BOUNDARY.md',
    contentClass: 'Navigation guidance',
    declaredItems: '4 human-led steps',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not orchestration, learner tracking, model prompting, lesson approval or teaching-effectiveness evidence.',
    nextEvidence: 'Build, link behavior, keyboard navigation, screen-reader order, visual review and human acceptance remain separate.',
  },
  {
    id: 'teaching-planning-packet',
    title: 'Teaching planning packet',
    sourcePath: 'web/src/TeachingPlanningPacketPanel.tsx',
    boundaryPath: 'docs/TEACHING_PLANNING_PACKET_BOUNDARY.md',
    contentClass: 'Navigation guidance',
    declaredItems: '4-bank subject/stage selector',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not curriculum acceptance, learner evidence, a lesson record, diagnosis, progression, delivery proof or evidence of effectiveness.',
    nextEvidence: 'Typecheck, build, all-combination selection, no-match, clipboard, accessibility, visual and human review remain separate.',
  },
  {
    id: 'teaching-bank-coverage',
    title: 'Teaching-bank coverage debt',
    sourcePath: 'web/src/TeachingBankCoveragePanel.tsx',
    boundaryPath: 'docs/TEACHING_BANK_COVERAGE_BOUNDARY.md',
    contentClass: 'Navigation guidance',
    declaredItems: '36 computed subject-stage cells across 4 banks',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Presence diagnostic only; not quality, completeness, suitability, curriculum coverage, accessibility, effectiveness or acceptance evidence.',
    nextEvidence: 'Typecheck, build, independent count comparison, filtering, accessibility, visual and human review remain separate.',
  },
  {
    id: 'teaching-data-authoring-queue',
    title: 'Teaching-data authoring queue',
    sourcePath: 'web/src/TeachingDataAuthoringQueuePanel.tsx',
    boundaryPath: 'docs/TEACHING_DATA_AUTHORING_QUEUE_BOUNDARY.md',
    contentClass: 'Navigation guidance',
    declaredItems: 'Computed missing-bank tasks across 36 subject-stage cells',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Not autonomous authoring, pedagogical priority, curriculum need, contribution approval, source edit or count reconciliation.',
    nextEvidence: 'Typecheck, build, independent task enumeration, template review, clipboard, accessibility, visual and human review remain separate.',
  },
  {
    id: 'teaching-data-draft-validator',
    title: 'Teaching-data draft validator',
    sourcePath: 'web/src/TeachingDataDraftValidatorPanel.tsx',
    boundaryPath: 'docs/TEACHING_DATA_DRAFT_VALIDATOR_BOUNDARY.md',
    contentClass: 'Navigation guidance',
    declaredItems: '4 structural draft contracts',
    author: 'Codex solo',
    crewActivity: 'none',
    crewResponse: 'none',
    externalAssistantUsed: false,
    externalAutomationUsed: false,
    evidenceStatus: 'Source present / not executed',
    authorityBoundary: 'Structural preflight only; not correctness, pedagogy, rights, accessibility, suitability, curriculum, approval, source contribution or runtime evidence.',
    nextEvidence: 'Typecheck, build, valid/invalid fixture review, duplicate detection, clipboard, accessibility, visual and human review remain separate.',
  },
];
