import { type Dispatch, FormEvent, type SetStateAction, useEffect, useRef, useState } from 'react';
import { focusWorkspaceSurface } from './workspace-navigation';
import './teaching-sessions.css';

type Lesson = { id: string; title: string; subject: string; learningStage: string; currentFingerprint: string };
type Receipt = { id: string; lessonId: string; lessonFingerprint: string; lessonReviewId: string; facilitatorIdentity: string; deliveredUtc: string; deliveryMode: string; deliveryState: string; deliveryContext: string; coveredContent: string; adaptations: string; interruptions: string; continuationNote: string; recordedUtc: string };
async function readJson<T>(endpoint: string, options?: RequestInit): Promise<T> { const response = await fetch(endpoint, options); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.state || `HTTP ${response.status}`); return payload as T; }
function localDateTime() { const now = new Date(); const offset = now.getTimezoneOffset() * 60000; return new Date(now.getTime() - offset).toISOString().slice(0, 16); }

export function TeachingSessionPanel() {
  const [lessons, setLessons] = useState<Lesson[]>([]); const [receipts, setReceipts] = useState<Receipt[]>([]);
  const [sessionId, setSessionId] = useState(''); const [lessonId, setLessonId] = useState(''); const [facilitator, setFacilitator] = useState('');
  const [delivered, setDelivered] = useState(localDateTime); const [mode, setMode] = useState('in-person'); const [deliveryState, setDeliveryState] = useState('delivery-finished');
  const [context, setContext] = useState(''); const [covered, setCovered] = useState(''); const [adaptations, setAdaptations] = useState('none');
  const [interruptions, setInterruptions] = useState('none'); const [continuation, setContinuation] = useState('none');
  const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [state, setState] = useState('Loading teaching-session receipts...');
  const [refreshing, setRefreshing] = useState(false); const refreshActive = useRef<Promise<void> | null>(null);
  async function refresh(afterCurrent = false) {
    if (refreshActive.current) { await refreshActive.current; if (!afterCurrent) return; }
    const request = (async () => { try { setState('Refreshing current teaching-session evidence...'); const data = await readJson<{ lessons: Lesson[]; receipts: Receipt[] }>('/api/teaching/sessions'); setLessons(data.lessons ?? []); setReceipts(data.receipts ?? []); setConfirmed(false); setState('Current local teaching-session evidence loaded. Review the selected lesson and confirm the final draft again.'); } catch (error) { setState(error instanceof Error ? error.message : 'Teaching-session receipts could not be loaded.'); } })();
    refreshActive.current = request; setRefreshing(true);
    try { await request; } finally { if (refreshActive.current === request) { refreshActive.current = null; setRefreshing(false); } }
  }
  useEffect(() => { void refresh(); }, []);
  const selected = lessons.find(value => value.id === lessonId);
  function updateDraft<T>(setter: Dispatch<SetStateAction<T>>, value: T) { setter(value); setConfirmed(false); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) { setState('Confirm the exact delivery-receipt boundary before writing.'); return; } setBusy(true); try {
    const parsed = new Date(delivered); if (Number.isNaN(parsed.getTime())) throw new Error('Choose a valid delivery date and time.');
    const result = await readJson<{ state: string; lessonFingerprint: string }>('/api/teaching/sessions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': 'record-teaching-session-receipt' }, body: JSON.stringify({ sessionId, lessonId, facilitatorIdentity: facilitator, deliveredUtc: parsed.toISOString(), deliveryMode: mode, deliveryState, deliveryContext: context, coveredContent: covered, adaptations, interruptions, continuationNote: continuation }) });
    setState(`${result.state} · ${result.lessonFingerprint}`); setConfirmed(false); await refresh(true);
  } catch (error) { setState(error instanceof Error ? error.message : 'Teaching-session receipt write failed.'); } finally { setBusy(false); } }
  return <section id="workspace-teaching-sessions" className="teaching-sessions" aria-labelledby="teaching-sessions-title"><header><div><p>DELIVERY RECEIPT · LOCAL EVIDENCE</p><h2 id="teaching-sessions-title">Record what was taught. Do not invent what was learned.</h2><span>Each immutable receipt binds one claimed session to the exact fingerprint of a currently approved lesson.</span></div><button type="button" onClick={() => void refresh()} disabled={busy || refreshing}>{refreshing ? 'Refreshing...' : 'Refresh'}</button></header>
    <div className="teaching-session-boundary"><strong>Evidence boundary</strong><span>This records activity, not attendance, attainment, effort, emotion, diagnosis, grade or mastery. Do not enter safeguarding, medical or unnecessary identifying data.</span></div>
    <form onSubmit={submit}><div className="teaching-session-fields"><label>Approved lesson<select required value={lessonId} onChange={event => updateDraft(setLessonId, event.target.value)}><option value="">Select a current approved lesson</option>{lessons.map(value => <option key={value.id} value={value.id}>{value.title} · {value.subject} · {value.learningStage}</option>)}</select></label><label>Stable session ID<input required pattern="[a-z0-9_-]{3,64}" value={sessionId} onChange={event => updateDraft(setSessionId, event.target.value)} /></label><label>Facilitator identity claim<input required minLength={2} maxLength={120} value={facilitator} onChange={event => updateDraft(setFacilitator, event.target.value)} /></label><label>Delivered date and time<input required type="datetime-local" value={delivered} onChange={event => updateDraft(setDelivered, event.target.value)} /></label><label>Delivery mode<select value={mode} onChange={event => updateDraft(setMode, event.target.value)}>{['in-person', 'remote', 'self-directed', 'other'].map(value => <option key={value}>{value}</option>)}</select></label><label>Activity state<select value={deliveryState} onChange={event => updateDraft(setDeliveryState, event.target.value)}>{['delivery-finished', 'delivery-paused', 'delivery-stopped', 'not-started'].map(value => <option key={value}>{value}</option>)}</select></label></div>
      {selected && <div className="teaching-session-selected"><div><strong>{selected.title}</strong><span>{selected.id} · {selected.subject} · {selected.learningStage}</span></div><code>{selected.currentFingerprint}</code><button type="button" onClick={() => focusWorkspaceSurface('workspace-lesson-reader')}>Open lesson reader</button></div>}
      <label>Delivery context<textarea required minLength={4} maxLength={1000} rows={2} value={context} onChange={event => updateDraft(setContext, event.target.value)} placeholder="Setting, resources and observation boundary; omit unnecessary personal data" /></label><label>Content actually covered<textarea required minLength={4} maxLength={4000} rows={3} value={covered} onChange={event => updateDraft(setCovered, event.target.value)} /></label><label>Adaptations actually used<textarea required minLength={4} maxLength={4000} rows={2} value={adaptations} onChange={event => updateDraft(setAdaptations, event.target.value)} /></label><label>Interruptions or safety stop<textarea required minLength={4} maxLength={4000} rows={2} value={interruptions} onChange={event => updateDraft(setInterruptions, event.target.value)} /></label><label>Continuation note<textarea required minLength={4} maxLength={4000} rows={2} value={continuation} onChange={event => updateDraft(setContinuation, event.target.value)} placeholder="Next operational step or reference to a correcting receipt" /></label>
      <label className="teaching-session-confirm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />I am recording a local activity receipt against this exact approved lesson. I am not recording a score, diagnosis, attendance claim or mastery decision.</label><button disabled={busy || refreshing || !selected || !confirmed}>Record immutable session receipt</button></form>
    <div className="teaching-session-ledger"><h3>Delivery ledger</h3>{receipts.length === 0 ? <p>No teaching-session receipts recorded.</p> : receipts.map(value => <article key={value.id}><header><strong>{value.id}</strong><em>{value.deliveryState}</em></header><p>{value.lessonId} · {value.facilitatorIdentity} · {value.deliveredUtc}</p><code>{value.lessonFingerprint}</code><footer><span>{value.deliveryMode}</span><span>Review {value.lessonReviewId}</span><span>Recorded {value.recordedUtc}</span></footer><details><summary>Recorded delivery detail</summary><p><b>Context:</b> {value.deliveryContext}</p><p><b>Covered:</b> {value.coveredContent}</p><p><b>Adaptations:</b> {value.adaptations}</p><p><b>Interruptions:</b> {value.interruptions}</p><p><b>Continuation:</b> {value.continuationNote}</p></details></article>)}</div><output>{state}</output></section>;
}
