import { useEffect, useMemo, useState } from 'react';
import { focusWorkspaceSurface } from './workspace-navigation';
import './teaching-operations.css';

type LessonOperation = { id: string; title: string; subject: string; learningStage: string; status: string; currentFingerprint: string; latestDecision?: string; latestReviewCurrent: boolean; reviewCount: number; sessionReceiptCount: number; currentSessionReceiptCount: number; checkCount: number; currentCheckCount: number; historicalCheckCount: number; attemptCount: number; currentAttemptCount: number; historicalAttemptCount: number; pendingAttemptCount: number; humanReviewedAttemptCount: number; pipelineState: string; pipelineLabel: string; nextAction: string; targetSurfaceId: string; evidenceBoundary: string };
async function readJson<T>(endpoint: string): Promise<T> { const response = await fetch(endpoint); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || `HTTP ${response.status}`); return payload as T; }

export function TeachingOperationsPanel() {
  const [lessons, setLessons] = useState<LessonOperation[]>([]); const [subject, setSubject] = useState('all'); const [pipeline, setPipeline] = useState('all');
  const [state, setState] = useState('Loading lesson pipeline evidence...'); const [busy, setBusy] = useState(false);
  async function refresh() { setBusy(true); try { const data = await readJson<{ lessons: LessonOperation[] }>('/api/teaching/operations'); setLessons(data.lessons ?? []); setState('Current read-only lesson pipeline evidence loaded.'); } catch (error) { setState(error instanceof Error ? error.message : 'Lesson pipeline evidence could not be loaded.'); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, []);
  const subjects = useMemo(() => Array.from(new Set(lessons.map(value => value.subject))).sort(), [lessons]);
  const states = useMemo(() => Array.from(new Map(lessons.map(value => [value.pipelineState, value.pipelineLabel])).entries()), [lessons]);
  const visible = useMemo(() => lessons.filter(value => (subject === 'all' || value.subject === subject) && (pipeline === 'all' || value.pipelineState === pipeline)), [lessons, subject, pipeline]);
  return <section id="workspace-teaching-operations" className="teaching-operations" aria-labelledby="teaching-operations-title"><header><div><p>LESSON PIPELINE · READ ONLY</p><h2 id="teaching-operations-title">Find the missing evidence, not a shortcut around it.</h2><span>Approval and delivery are fingerprint-bound. Practice counts are historical until their alignment is inspected.</span></div><button type="button" onClick={() => void refresh()} disabled={busy}>Refresh</button></header>
    <div className="teaching-operations-boundary"><strong>No automatic progression</strong><span>Current practice means schema-v2 checks whose fingerprint matches this lesson. Legacy and stale rows remain visible history and cannot accept new attempts.</span></div>
    <div className="teaching-operation-filters"><label>Subject<select value={subject} onChange={event => setSubject(event.target.value)}><option value="all">All subjects</option>{subjects.map(value => <option key={value}>{value}</option>)}</select></label><label>Pipeline evidence<select value={pipeline} onChange={event => setPipeline(event.target.value)}><option value="all">All states</option>{states.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>
    <p className="teaching-operation-count" role="status">Showing {visible.length} of {lessons.length} saved lessons.</p>
    <div className="teaching-operation-grid">{visible.length === 0 ? <p>No lesson matches this evidence filter.</p> : visible.map(value => <article key={value.id} data-pipeline={value.pipelineState}><header><div><p>{value.subject.toUpperCase()} · {value.learningStage.toUpperCase()}</p><h3>{value.title}</h3></div><strong>{value.pipelineLabel}</strong></header><code>{value.currentFingerprint}</code><dl><div><dt>Reviews</dt><dd>{value.reviewCount}</dd></div><div><dt>Current deliveries</dt><dd>{value.currentSessionReceiptCount}/{value.sessionReceiptCount}</dd></div><div><dt>Current checks</dt><dd>{value.currentCheckCount}</dd></div><div><dt>Historical checks</dt><dd>{value.historicalCheckCount}</dd></div><div><dt>Current attempts</dt><dd>{value.currentAttemptCount}</dd></div><div><dt>Historical attempts</dt><dd>{value.historicalAttemptCount}</dd></div><div><dt>Pending human review</dt><dd>{value.pendingAttemptCount}</dd></div><div><dt>Human reviewed</dt><dd>{value.humanReviewedAttemptCount}</dd></div></dl><aside><b>Evidence boundary</b><span>{value.evidenceBoundary}</span></aside><footer><span>{value.nextAction}</span><button type="button" onClick={() => focusWorkspaceSurface(value.targetSurfaceId)}>Open relevant surface</button></footer></article>)}</div><output>{state}</output></section>;
}
