import { FormEvent, useEffect, useState } from 'react';
import './teaching-reference-review.css';
import './reference-review-cadence.css';

type Source = { id: string; publisher: string; title: string; sourceUrl: string; scope: string; useBoundary: string };
type SourceState = { sourceId: string; currentFingerprint: string; latestDisposition?: string; latestReviewCurrent: boolean; nextReviewDate?: string; reviewCount: number };
type Review = { id: string; sourceId: string; sourceFingerprint: string; reviewerIdentity: string; disposition: string; linkState: string; rightsState: string; summaryState: string; nextReviewDate: string; note: string; reviewedUtc: string; fingerprintCurrent: boolean };
const dispositions = ['current-reviewed', 'needs-update', 'retired-from-guidance', 'deferred']; const linkStates = ['reachable', 'redirected-reviewed', 'unreachable', 'not-checked']; const rightsStates = ['reviewed', 'needs-review', 'not-applicable']; const summaryStates = ['matches-current-source', 'needs-update', 'not-checked'];
async function readJson<T>(endpoint: string, options?: RequestInit): Promise<T> { const response = await fetch(endpoint, options); const payload = await response.json(); if (!response.ok || payload.ok === false) throw new Error(payload.error || payload.state || `HTTP ${response.status}`); return payload as T; }
function localCalendarDate() { const value = new Date(); return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function cadenceState(value?: string) { if (!value) return 'UNSCHEDULED'; const today = localCalendarDate(); return value < today ? 'OVERDUE' : value === today ? 'DUE TODAY' : 'SCHEDULED'; }

export function TeachingReferenceReviewPanel() {
  const [sources, setSources] = useState<Source[]>([]); const [states, setStates] = useState<SourceState[]>([]); const [reviews, setReviews] = useState<Review[]>([]);
  const [sourceId, setSourceId] = useState(''); const [reviewId, setReviewId] = useState(''); const [reviewer, setReviewer] = useState('');
  const [disposition, setDisposition] = useState(dispositions[3]); const [linkState, setLinkState] = useState(linkStates[3]); const [rightsState, setRightsState] = useState(rightsStates[1]); const [summaryState, setSummaryState] = useState(summaryStates[2]);
  const [nextReviewDate, setNextReviewDate] = useState(''); const [note, setNote] = useState(''); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('Loading reference governance...');
  async function refresh() { setConfirmed(false); try { const data = await readJson<{ sources: Source[]; sourceStates: SourceState[]; reviews: Review[] }>('/api/teaching/references'); setSources(data.sources ?? []); setStates(data.sourceStates ?? []); setReviews(data.reviews ?? []); setStatus('Current reference and review evidence loaded. No source was fetched. Reconfirm after inspecting the exact source fingerprint and review evidence.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Reference review evidence could not be loaded.'); } }
  useEffect(() => { void refresh(); }, []); const selected = sources.find(value => value.id === sourceId); const selectedState = states.find(value => value.sourceId === sourceId);
  function updateField(setter: (value: string) => void, value: string) { setConfirmed(false); setter(value); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!confirmed) { setStatus('Confirm the immutable review boundary before writing.'); return; } setBusy(true); try { const result = await readJson<{ state: string; sourceFingerprint: string }>('/api/teaching/reference-reviews', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-MA-Teacher-Intent': 'review-teaching-reference' }, body: JSON.stringify({ reviewId, sourceId, reviewerIdentity: reviewer, disposition, linkState, rightsState, summaryState, nextReviewDate, note }) }); setStatus(`${result.state} · ${result.sourceFingerprint}`); setConfirmed(false); await refresh(); } catch (error) { setStatus(error instanceof Error ? error.message : 'Reference review write failed.'); } finally { setBusy(false); } }
  return <section id="workspace-reference-review" className="teaching-reference-review" aria-labelledby="teaching-reference-review-title"><header><div><p>REFERENCE GOVERNANCE · NO AUTOMATIC REFRESH</p><h2 id="teaching-reference-review-title">Record what was actually checked.</h2><span>Review source reachability, rights and editorial fidelity without rewriting the registry.</span></div><button type="button" onClick={() => void refresh()} disabled={busy}>Refresh local evidence</button></header>
    <div className="reference-review-boundary"><strong>Boundary</strong><span>A current-reviewed receipt is evidence of a recorded review, not proof that the source is universally applicable or that its guidance caused learning.</span></div>
    <div className="reference-review-schedule" aria-label="Teaching reference review schedule">{states.map(value => { const source = sources.find(candidate => candidate.id === value.sourceId); return <article key={value.sourceId} className={!value.latestReviewCurrent && value.reviewCount > 0 ? 'stale' : cadenceState(value.nextReviewDate).toLowerCase().replaceAll(' ', '-')}><div><strong>{source?.title ?? value.sourceId}</strong><span>{source?.publisher ?? value.sourceId}</span></div><em>{value.latestDisposition ?? 'never-reviewed'}</em><span>{value.latestReviewCurrent ? 'CURRENT FINGERPRINT' : value.reviewCount > 0 ? 'STALE FINGERPRINT' : 'NO REVIEW'}</span><b>{cadenceState(value.nextReviewDate)}{value.nextReviewDate ? ` · ${value.nextReviewDate}` : ''}</b></article>; })}</div>
    <form onSubmit={submit}><div className="reference-review-fields"><label>Source<select required value={sourceId} onChange={event => updateField(setSourceId, event.target.value)}><option value="">Select a source</option>{sources.map(value => <option key={value.id} value={value.id}>{value.publisher} · {value.title}</option>)}</select></label><label>Stable review ID<input required pattern="[a-z0-9_-]{3,64}" value={reviewId} onChange={event => updateField(setReviewId, event.target.value)} /></label><label>Reviewer identity<input required maxLength={120} value={reviewer} onChange={event => updateField(setReviewer, event.target.value)} /></label><label>Disposition<select value={disposition} onChange={event => updateField(setDisposition, event.target.value)}>{dispositions.map(value => <option key={value}>{value}</option>)}</select></label><label>Link state<select value={linkState} onChange={event => updateField(setLinkState, event.target.value)}>{linkStates.map(value => <option key={value}>{value}</option>)}</select></label><label>Rights state<select value={rightsState} onChange={event => updateField(setRightsState, event.target.value)}>{rightsStates.map(value => <option key={value}>{value}</option>)}</select></label><label>Summary state<select value={summaryState} onChange={event => updateField(setSummaryState, event.target.value)}>{summaryStates.map(value => <option key={value}>{value}</option>)}</select></label><label>Next review date<input required type="date" value={nextReviewDate} onChange={event => updateField(setNextReviewDate, event.target.value)} /></label></div>
      {selected && <aside><div><strong>{selected.title}</strong><span>{selected.publisher}</span></div><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Open source in browser</a><p>{selected.scope}</p><p>{selected.useBoundary}</p><code>{selectedState?.currentFingerprint}</code><span>{selectedState?.latestDisposition ?? 'never reviewed'} · {selectedState?.latestReviewCurrent ? 'current fingerprint' : 'no current review'}</span></aside>}
      <label>Review note<textarea required minLength={5} maxLength={4000} rows={5} value={note} onChange={event => updateField(setNote, event.target.value)} placeholder="What was checked, what changed, and what remains uncertain" /></label><label className="reference-review-confirm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />Record this immutable review without changing source metadata or editorial principles.</label><button disabled={busy || !selected || !confirmed}>Record reference review</button></form>
    <div className="reference-review-ledger"><h3>Review ledger</h3>{reviews.length === 0 ? <p>No reference reviews recorded.</p> : reviews.map(value => <article key={value.id}><header><strong>{value.id}</strong><em>{value.disposition}</em></header><p>{value.sourceId} · {value.reviewerIdentity} · {value.reviewedUtc}</p><code>{value.sourceFingerprint}</code><dl><div><dt>Link</dt><dd>{value.linkState}</dd></div><div><dt>Rights</dt><dd>{value.rightsState}</dd></div><div><dt>Summary</dt><dd>{value.summaryState}</dd></div><div><dt>Next review</dt><dd>{value.nextReviewDate}</dd></div></dl><p>{value.note}</p><footer>{value.fingerprintCurrent ? 'CURRENT FINGERPRINT' : 'STALE FINGERPRINT'}</footer></article>)}</div><output>{status}</output></section>;
}
