export const vocabularyEntries = [
  {
    id: 'english-claim', subject: 'English', term: 'claim', stages: ['ks1', 'ks2', 'ks3'], stageLabel: 'KS1-KS3 lens',
    learnerMeaning: 'An idea that a speaker or writer says is true or wants the audience to accept.',
    disciplinaryPrecision: 'A claim is distinct from the evidence, reasoning, example, or quotation used to support it.',
    modelUse: 'Claim: the path was difficult to use. Evidence: loose stones moved under every step.',
    nonExample: 'Retelling every event without identifying the idea being supported.',
    retrievalPrompt: 'What is the claim, and which words show the evidence rather than the claim?',
    caution: 'Not every interpretation has one fixed claim; alternatives can be warranted when evidence is explicit.',
  },
  {
    id: 'english-evidence', subject: 'English', term: 'evidence', stages: ['ks2', 'ks3', 'ks4'], stageLabel: 'KS2-KS4 lens',
    learnerMeaning: 'A detail used to support, test, or challenge an idea about a text.',
    disciplinaryPrecision: 'Quotation alone is not explanation. The response must connect the selected detail to the claim or interpretation.',
    modelUse: 'The moving stones support the claim because unstable footing makes the path harder to cross.',
    nonExample: 'Copying a long paragraph without stating what it supports.',
    retrievalPrompt: 'Which smallest relevant detail supports the idea, and how does it do so?',
    caution: 'Evidence in English is not identical to scientific measurement or historical provenance; preserve the subject context.',
  },
  {
    id: 'mathematics-equivalent', subject: 'Mathematics', term: 'equivalent', stages: ['ks2', 'ks3'], stageLabel: 'KS2-KS3 lens',
    learnerMeaning: 'Different-looking mathematical forms that have the same value or represent the same quantity.',
    disciplinaryPrecision: 'Equivalence is a relation that must be justified using structure, transformation, representation, or calculation.',
    modelUse: 'Three quarters and six eighths are equivalent because halving each quarter changes the number of parts without changing the proportion.',
    nonExample: 'Calling two fractions equivalent only because their numerators are close.',
    retrievalPrompt: 'What stayed unchanged, and which operation changed the representation?',
    caution: 'The equals sign expresses equivalence, not an instruction meaning “write the answer next.”',
  },
  {
    id: 'mathematics-intercept', subject: 'Mathematics', term: 'intercept', stages: ['ks3', 'ks4'], stageLabel: 'KS3-KS4 lens',
    learnerMeaning: 'A point where a graph crosses an axis; in y = mx + c, c is the y-intercept.',
    disciplinaryPrecision: 'The intercept is an axis-crossing value, not the constant rate of change represented by the gradient.',
    modelUse: 'For y = 3x - 2, the y-intercept is -2 because y = -2 when x = 0.',
    nonExample: 'Calling 3 the intercept because values increase by 3.',
    retrievalPrompt: 'What is the output when the input is zero, and what does that locate on the graph?',
    caution: 'Do not teach the formula label without connecting table, graph, equation, and context.',
  },
  {
    id: 'science-observation', subject: 'Science', term: 'observation', stages: ['ks1', 'ks2', 'ks3'], stageLabel: 'KS1-KS3 lens',
    learnerMeaning: 'Information noticed or measured directly using senses or suitable instruments.',
    disciplinaryPrecision: 'An observation records available evidence; it must remain separate from an inferred mechanism or explanation.',
    modelUse: 'Droplets were visible on the outside of the sealed cold cup.',
    nonExample: 'Water vapour condensed because the cup was cold; that is an explanatory inference.',
    retrievalPrompt: 'What was directly seen or measured, and what part is an explanation?',
    caution: 'A measurement needs units, method, and instrument context; seeing is not the only form of observation.',
  },
  {
    id: 'science-inference', subject: 'Science', term: 'inference', stages: ['ks2', 'ks3', 'ks4'], stageLabel: 'KS2-KS4 lens',
    learnerMeaning: 'An explanation or conclusion worked out from observations and existing knowledge.',
    disciplinaryPrecision: 'An inference can be well supported without being directly observed and may change when new evidence distinguishes alternatives.',
    modelUse: 'The droplets may have formed when water vapour in surrounding air condensed on the cold surface.',
    nonExample: 'Droplets were present; that is the observation itself.',
    retrievalPrompt: 'Which evidence supports this explanation, and what additional observation could test it?',
    caution: 'Do not present a plausible inference as certain merely because it is familiar.',
  },
  {
    id: 'history-continuity', subject: 'History and histories', term: 'continuity', stages: ['ks2', 'ks3', 'ks4'], stageLabel: 'KS2-KS4 lens',
    learnerMeaning: 'Something that remains or develops without a complete break across a period of time.',
    disciplinaryPrecision: 'Continuity is evaluated alongside change and can operate differently across groups, places, scales, and timespans.',
    modelUse: 'The fictional market moved indoors, but it continued to take place on Friday beside the bridge.',
    nonExample: 'Saying nothing changed because one feature remained.',
    retrievalPrompt: 'What changed, what continued, and for whom or over which dates?',
    caution: 'Avoid treating one source or one group’s experience as universal continuity.',
  },
  {
    id: 'history-provenance', subject: 'History and histories', term: 'provenance', stages: ['ks3', 'ks4', 'post16-adult'], stageLabel: 'KS3-adult lens',
    learnerMeaning: 'Information about where a source came from, including who made it, when, for whom, and why.',
    disciplinaryPrecision: 'Provenance helps judge what questions a source can address; it does not mechanically make a source reliable or unreliable.',
    modelUse: 'A committee note records the committee’s intended timetable change, not every worker’s response.',
    nonExample: 'Rejecting a source only because its creator had a purpose.',
    retrievalPrompt: 'Who created this, for which audience and purpose, and what claim can it support?',
    caution: 'A purpose can make a source especially useful for one question while limiting another.',
  },
  {
    id: 'languages-register', subject: 'Languages', term: 'register', stages: ['ks2', 'ks3', 'ks4', 'post16-adult'], stageLabel: 'KS2-adult lens',
    learnerMeaning: 'Language choices that fit the relationship, purpose, setting, and level of formality.',
    disciplinaryPrecision: 'Register includes pronouns, verb forms, vocabulary, politeness conventions, tone, and culturally situated expectations.',
    modelUse: 'French “tu” suits a stated informal peer exchange; “je voudrais” can frame a polite service request.',
    nonExample: 'Treating one memorised polite phrase as appropriate in every community or situation.',
    retrievalPrompt: 'Who is speaking to whom, for what purpose, and which language choice signals that relationship?',
    caution: 'Register varies by community, region, age, context, and language; qualified review is required.',
  },
  {
    id: 'languages-cognate', subject: 'Languages', term: 'cognate', stages: ['ks3', 'ks4', 'post16-adult'], stageLabel: 'KS3-adult lens',
    learnerMeaning: 'A word related to a word in another language through shared linguistic history, often with similar form and meaning.',
    disciplinaryPrecision: 'Visual similarity is a clue, not proof; pronunciation, meaning, grammar, and false friends require checking.',
    modelUse: 'French “important” and English “important” are closely related and overlap in meaning.',
    nonExample: 'Assuming every similar-looking word has the same meaning, such as treating a false friend as evidence.',
    retrievalPrompt: 'Which part looks familiar, what meaning is proposed, and how could context or a source verify it?',
    caution: 'Do not reduce language learning to guessing from English or imply English is the universal reference point.',
  },
  {
    id: 'computing-sequence', subject: 'Computing and IT', term: 'sequence', stages: ['early-learning', 'ks1', 'ks2'], stageLabel: 'Early learning-KS2 lens',
    learnerMeaning: 'Instructions arranged in the order they will be carried out.',
    disciplinaryPrecision: 'Sequence determines execution order; changing the order can change state, route, output, or whether a goal is reached.',
    modelUse: 'Forward, turn right, forward produces a different route from turn right, forward, forward.',
    nonExample: 'Listing useful commands without deciding their execution order.',
    retrievalPrompt: 'What happens after each instruction, and where does the state or position end?',
    caution: 'For early learning, use supervised concrete action and do not infer abstract programming mastery.',
  },
  {
    id: 'early-english-event', subject: 'English', term: 'event', stages: ['early-learning'], stageLabel: 'Early learning lens',
    learnerMeaning: 'Something that happens in a story, shared account, or sequence.',
    disciplinaryPrecision: 'An event is one occurrence; a story may connect events through order, cause, character action, or change.',
    modelUse: 'The bridge breaks is one event; the characters finding another route is a later event.',
    nonExample: 'Naming a character without saying what happens.',
    retrievalPrompt: 'What happened, and what was different after it happened?',
    caution: 'Accept action, gesture, picture choice, drawing, sign, and supported communication; do not make spoken retelling or recall speed the evidence gate.',
  },
  {
    id: 'early-mathematics-pattern', subject: 'Mathematics', term: 'pattern', stages: ['early-learning'], stageLabel: 'Early learning lens',
    learnerMeaning: 'An arrangement or change that follows a rule we can notice and continue.',
    disciplinaryPrecision: 'A pattern requires a repeatable or describable relationship; visual decoration alone does not establish the rule.',
    modelUse: 'Red, blue, red, blue follows an alternating rule, so the next item is red if the rule continues.',
    nonExample: 'A mixed row of objects with no identified relationship.',
    retrievalPrompt: 'What is repeating or changing, and what would come next if the same rule continues?',
    caution: 'Ask the learner to show the rule before correcting an unexpected continuation; a different consistent rule may be valid.',
  },
  {
    id: 'early-science-change', subject: 'Science', term: 'change', stages: ['early-learning'], stageLabel: 'Early learning lens',
    learnerMeaning: 'A difference we can notice between before and after.',
    disciplinaryPrecision: 'Describing a change is an observation; explaining why it happened is a separate inference that can be investigated.',
    modelUse: 'The ice was solid before and became liquid afterwards; melting names the observed change.',
    nonExample: 'Saying it changed because it wanted to without identifying an observable difference.',
    retrievalPrompt: 'What was it like before, what is it like now, and how did you notice?',
    caution: 'Use safe accessible observation routes and never require touch, taste, hearing, or vision as the only way to establish change.',
  },
  {
    id: 'early-history-before', subject: 'History and histories', term: 'before', stages: ['early-learning'], stageLabel: 'Early learning lens',
    learnerMeaning: 'Earlier in an ordered story, routine, or account.',
    disciplinaryPrecision: 'Before expresses relative chronology: one event comes earlier than another. It does not by itself state how long ago either event occurred.',
    modelUse: 'Putting on socks came before putting on shoes in the demonstrated routine.',
    nonExample: 'Calling one picture old only because it is black and white.',
    retrievalPrompt: 'Which happened earlier, and what clue supports that order?',
    caution: 'Use consented shared examples and avoid assumptions about family structure, homes, possessions, photographs, or personal memories.',
  },
  {
    id: 'computing-state', subject: 'Computing and IT', term: 'state', stages: ['ks3', 'ks4', 'post16-adult'], stageLabel: 'KS3-adult lens',
    learnerMeaning: 'The information a system or program currently holds at a particular step.',
    disciplinaryPrecision: 'State can include variable values, component modes, stored data, or external conditions; tracing requires naming what changes and what remains.',
    modelUse: 'In a running-total loop, total changes from 0 to 2 to 5 to 9 as each item is processed.',
    nonExample: 'Giving only the final output without tracking intermediate values.',
    retrievalPrompt: 'What is the state before this step, which operation runs, and what is the state afterwards?',
    caution: 'A trace supports reasoning about observed code; it does not prove the environment, inputs, or hidden dependencies are correct.',
  },
] as const;

export type VocabularyEntry = typeof vocabularyEntries[number];
