export const workedExamples = [
  {
    id: 'english-claim-evidence',
    subject: 'English',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Separate a claim from its evidence',
    sourceBoundary: 'Synthetic paragraph authored for this demonstration. It is not curriculum evidence and must be replaced by reviewed stage-specific evidence.',
    learningIntention: 'Identify a claim and explain how one detail supports it.',
    model: 'Paragraph: “The path was difficult to use. Rain had filled its deepest cracks, and two loose stones moved under every step.” Claim: the path was difficult to use. Evidence: the filled cracks and moving stones. The details support the claim because they describe obstacles and unstable footing.',
    checkPrompt: 'State the claim. Quote or describe one supporting detail. Explain the connection in one sentence.',
    successCriteria: ['Names the claim rather than retelling the whole paragraph.', 'Selects a relevant detail.', 'Explains why the detail supports the claim.'],
    sampleAttempt: 'The claim is that the path was difficult. The stones moved. This could make someone lose balance, so it supports the claim.',
    humanReview: 'Met for this attempt: claim, relevant detail, and connection are all visible. This does not establish broad reading attainment.',
    nextEvidence: 'Use a second paragraph where evidence is less physically obvious and inspect whether the same distinction transfers.',
  },
  {
    id: 'mathematics-equivalent-fractions',
    subject: 'Mathematics',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Explain equivalent fractions with structure',
    sourceBoundary: 'Original worked example. It is not a programme-of-study statement or proof of stage suitability.',
    learningIntention: 'Explain why 3/4 and 6/8 name the same proportion.',
    model: 'Split one same-sized rectangle into 4 equal parts and shade 3. Split an identical rectangle into 8 equal parts by halving every quarter; 6 eighths are shaded. Both numerator and denominator doubled, while the shaded proportion stayed unchanged.',
    checkPrompt: 'Show whether 2/3 and 4/6 are equivalent using a representation and one explanation.',
    successCriteria: ['Uses equal wholes.', 'Represents both fractions accurately.', 'Explains that numerator and denominator changed by the same factor while the proportion stayed equal.'],
    sampleAttempt: 'I divided both same-sized bars into thirds, then split each third in half. Two thirds covered the same length as four sixths, so they are equivalent.',
    humanReview: 'Met for this representation and explanation. No speed, grade, or general fraction mastery is inferred.',
    nextEvidence: 'Test a non-equivalent close case and ask which structural condition fails.',
  },
  {
    id: 'science-observation-inference',
    subject: 'Science',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Distinguish observation from inference',
    sourceBoundary: 'Original safe desk-based scenario. It is not an authorization for unsupervised practical work or a curriculum statement.',
    learningIntention: 'Separate what was observed from an explanation inferred from it.',
    model: 'Scenario: droplets appear on the outside of a sealed cup containing cold water. Observation: visible droplets formed on the outside surface. Inference: water vapour in the surrounding air may have condensed on the cold surface. The inference uses a model; it was not seen directly.',
    checkPrompt: 'Write one observation and one inference from the scenario. Label each and explain the difference.',
    successCriteria: ['Observation describes directly available evidence.', 'Inference offers a plausible explanation.', 'The response does not present the explanation as something directly seen.'],
    sampleAttempt: 'Observation: drops appeared outside the cup. Inference: water in the air changed to liquid on the cold cup. I could see the drops but not the change happening molecule by molecule.',
    humanReview: 'Met for the distinction in this scenario. Accuracy and stage-specific model language still require subject review.',
    nextEvidence: 'Provide a second observation with two plausible explanations and ask what additional evidence would discriminate between them.',
  },
  {
    id: 'history-source-provenance',
    subject: 'History and histories',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Ask what a source can support',
    sourceBoundary: 'Entirely fictional meeting-note extract created for workflow demonstration. It supplies no evidence about a real past event.',
    learningIntention: 'Use provenance to bound a historical claim.',
    model: 'Fictional extract: “Meeting note, Northbridge Works committee, 14 March 1890: the new bell will begin the morning shift ten minutes earlier.” Direct support: the committee recorded an intended timetable change. It does not by itself prove workers agreed, the change happened, or how every worker experienced it.',
    checkPrompt: 'State one claim the fictional note could support and one claim it could not support alone. Explain why.',
    successCriteria: ['Uses the source creator, date, form, or purpose.', 'Keeps the supported claim close to the extract.', 'Names missing evidence for the unsupported claim.'],
    sampleAttempt: 'It supports that the committee intended an earlier start. It cannot prove workers accepted it because no worker response is included.',
    humanReview: 'Met for this fictional source-evaluation task. It is not evidence of knowledge about a real period or event.',
    nextEvidence: 'Add a conflicting fictional worker letter and inspect how the account changes without treating either source as complete truth.',
  },
  {
    id: 'languages-greeting-exchange',
    subject: 'Languages',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Use a greeting and name exchange for meaning',
    sourceBoundary: 'Original French micro-example for demonstrating the workflow. Register, pronunciation, cultural context, and stage suitability require a qualified human review.',
    learningIntention: 'Understand and produce a short informal greeting and name exchange.',
    model: 'Speaker A: “Bonjour. Je m’appelle Maya. Comment tu t’appelles ?” Speaker B: “Bonjour. Je m’appelle Sam.” Notice the greeting, name statement, and return question. The informal “tu” form is a contextual choice, not a universal default.',
    checkPrompt: 'Complete a two-person informal greeting and name exchange, then identify the greeting and question.',
    successCriteria: ['Meaning is intelligible.', 'A greeting and name statement are present.', 'The response includes or recognizes the return question.', 'Register remains appropriate to the stated informal scenario.'],
    sampleAttempt: 'Bonjour. Je m’appelle Sam. Comment tu t’appelles ?',
    humanReview: 'Partially met in isolation: the required language is present, but listening, pronunciation, response to a partner, and independent transfer were not observed.',
    nextEvidence: 'Use a short spoken exchange with a different name and inspect comprehension before written recall.',
  },
  {
    id: 'computing-trace-state',
    subject: 'Computing and IT',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Trace program state before changing code',
    sourceBoundary: 'Original language-neutral pseudocode. It is not tied to a qualification, programming language, or configured curriculum statement.',
    learningIntention: 'Trace how a variable changes through a simple loop.',
    model: 'Pseudocode: total = 0; for each n in [2, 3, 4], set total = total + n. Trace: start 0; after 2 → 2; after 3 → 5; after 4 → 9. The final value follows from each state change, not a guess from the list.',
    checkPrompt: 'Trace total for [1, 4, 2] and record its value after every iteration.',
    successCriteria: ['Starts from the initialized value.', 'Processes items in order.', 'Records each intermediate state.', 'Final result matches the trace.'],
    sampleAttempt: 'Start 0; after 1 it is 1; after 4 it is 5; after 2 it is 7. Final total 7.',
    humanReview: 'Met for this loop trace. It does not establish ability to write loops, debug another program, or explain iteration generally.',
    nextEvidence: 'Change the update expression or initial value and ask the learner to predict, trace, and explain the changed result.',
  },
  {
    id: 'english-sequence-retell',
    subject: 'English',
    stage: 'ks1',
    stageLabel: 'Key Stage 1 lens',
    title: 'Sequence a short event without inventing detail',
    sourceBoundary: 'Original three-sentence micro-story. The KS1 label is a planning lens, not reviewed curriculum alignment or proof of reading suitability.',
    learningIntention: 'Put three stated events in order and retell them using sequence words.',
    model: 'Micro-story: “Ari found a seed. Ari pressed it into damp soil. Later, a green shoot appeared.” Model retell: First Ari found a seed. Next Ari planted it in damp soil. Later a green shoot appeared. The retell keeps the stated order and does not add an unstated cause or timescale.',
    checkPrompt: 'Order three event cards from the story, then retell them using first, next, and later.',
    successCriteria: ['Places all three stated events in story order.', 'Uses sequence language to connect the events.', 'Does not add an event that the short text did not state.'],
    sampleAttempt: 'First Ari found the seed. Next Ari put it in the soil. Later the green shoot came up.',
    humanReview: 'Met for sequencing and bounded retell in this synthetic text. Decoding, oral-language independence, writing fluency, and transfer were not established.',
    nextEvidence: 'Use a second short sequence with one distracting illustration detail and inspect whether text order remains the basis of the retell.',
  },
  {
    id: 'mathematics-linear-change',
    subject: 'Mathematics',
    stage: 'ks4',
    stageLabel: 'Key Stage 4 lens',
    title: 'Compare a linear rule with its table',
    sourceBoundary: 'Original algebra example. The KS4 label does not establish qualification coverage, exam-board wording, accessibility, or reviewed curriculum alignment.',
    learningIntention: 'Connect the rule y = 3x - 2 to corresponding values and explain the constant rate of change.',
    model: 'For x values 0, 1, 2, and 3, the rule gives y values -2, 1, 4, and 7. Each increase of 1 in x increases y by 3. The value -2 when x = 0 is the intercept; it is not the step size.',
    checkPrompt: 'Complete a table for y = 4x + 1 at x = -1, 0, 1, and 2. Identify the step change and intercept, then verify one row by substitution.',
    successCriteria: ['Substitutes each x value accurately.', 'Distinguishes the coefficient step change from the intercept.', 'Shows one explicit substitution that reproduces its table value.'],
    sampleAttempt: 'The y values are -3, 1, 5, 9. They go up by 4 each time and the intercept is 1. For x = 2, 4(2) + 1 = 9.',
    humanReview: 'Met for this rule, table, and substitution. Graph interpretation, rearrangement, non-linear comparison, and qualification performance remain untested.',
    nextEvidence: 'Present a table with one erroneous row and ask for evidence identifying whether the rule, substitution, or arithmetic caused the mismatch.',
  },
  {
    id: 'science-material-sort',
    subject: 'Science',
    stage: 'ks1',
    stageLabel: 'Key Stage 1 lens',
    title: 'Sort objects by one observable property',
    sourceBoundary: 'Original desk-based sorting scenario using ordinary classroom objects. The KS1 label is a planning lens and does not replace safety, curriculum, or age-suitability review.',
    learningIntention: 'Group objects using one named observable property and describe the rule used.',
    model: 'Objects: clear plastic ruler, wooden block, metal spoon, clear glass jar. Sort rule: lets light through / does not let light through. The ruler and jar may be grouped as letting light through; the block and spoon do not. Material name and transparency are different descriptions.',
    checkPrompt: 'Sort four supplied safe objects by one visible or touch-observable property. Name the rule and explain where each object belongs.',
    successCriteria: ['Names one observable property before or after sorting.', 'Applies the same rule to every object.', 'Describes observations without claiming an unseen material property.'],
    sampleAttempt: 'I sorted them into bendy and not bendy. The foam and rubber strip bent, but the wooden cube and metal spoon did not bend when I gently tried them.',
    humanReview: 'Met for a consistent observed sorting rule in the stated safe interaction. Material classification, vocabulary breadth, and independent investigation planning were not established.',
    nextEvidence: 'Ask for a different valid sorting rule on the same objects and compare how changing the property changes group membership.',
  },
  {
    id: 'history-change-continuity',
    subject: 'History and histories',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Separate change from continuity in fictional evidence',
    sourceBoundary: 'Original fictional town records created only for this demonstration. They provide no evidence about a real place, period, or community.',
    learningIntention: 'Identify one change and one continuity between two dated fictional records.',
    model: 'Fictional records: 1840 map note, “Market held beside the bridge each Friday.” 1890 directory, “Friday market now held in the covered hall beside the bridge.” Change: the market moved indoors. Continuity: it remained on Friday and beside the bridge. The records do not explain why the hall was built.',
    checkPrompt: 'State one evidenced change, one evidenced continuity, and one question these two fictional records cannot answer.',
    successCriteria: ['Uses both dates in the comparison.', 'Distinguishes what changed from what remained.', 'Names a missing explanation rather than inventing a cause.'],
    sampleAttempt: 'The market changed from outside to a covered hall. It stayed on Friday near the bridge. The records do not tell us why people moved it indoors.',
    humanReview: 'Met for this bounded comparison. Chronological scale, real contextual knowledge, source reliability, and broader historical explanation were not assessed.',
    nextEvidence: 'Add a third fictional source with a competing description and inspect whether the learner revises the account without discarding earlier evidence.',
  },
  {
    id: 'languages-formal-request',
    subject: 'Languages',
    stage: 'post16-adult',
    stageLabel: 'Post-16 and adult lens',
    title: 'Choose register in a practical French request',
    sourceBoundary: 'Original French service-counter micro-dialogue. The adult label is a dignity and context lens; linguistic accuracy, culture, dialect, pronunciation, and route-specific suitability require qualified review.',
    learningIntention: 'Make and respond to a short polite request using an appropriate formal register.',
    model: 'Customer: “Bonjour, je voudrais un billet pour Lyon, s’il vous plaît.” Staff: “Aller simple ou aller-retour ?” Customer: “Aller-retour, merci.” “Je voudrais” frames a polite request; the exchange still needs listening and clarification skills beyond memorising one sentence.',
    checkPrompt: 'Adapt the exchange to request two return tickets to another destination, then identify the polite request phrase and the clarification question.',
    successCriteria: ['Communicates destination, quantity, and return-ticket meaning.', 'Uses a polite request appropriate to the stated service context.', 'Recognizes and answers the clarification question.'],
    sampleAttempt: 'Bonjour, je voudrais deux billets aller-retour pour Lille, s’il vous plaît. The polite phrase is “je voudrais” and the question asks one-way or return.',
    humanReview: 'Partially met from written evidence: meaning and register are visible, but spoken comprehension, intelligibility, spontaneous repair, and real service interaction were not observed.',
    nextEvidence: 'Use a short audio exchange with a changed destination and one unexpected clarification, then record only the directly observed response evidence.',
  },
  {
    id: 'computing-instruction-sequence',
    subject: 'Computing and IT',
    stage: 'early-learning',
    stageLabel: 'Early-learning reference lens',
    title: 'Sequence instructions for a floor-grid route',
    sourceBoundary: 'Original unplugged activity. EYFS and early-learning curriculum alignment is reference-only; adult supervision, physical access, language demand, and developmental suitability require review.',
    learningIntention: 'Put simple movement instructions in an order that reaches a visible goal.',
    model: 'On a three-square floor path, the toy starts facing forward and the goal is two squares ahead. Model sequence: forward, forward. Run each card in order and stop at the goal. Changing the order changes what happens when turns are included.',
    checkPrompt: 'Choose and order movement cards to move a toy from the marked start to the marked goal, then run the sequence one card at a time.',
    successCriteria: ['Starts from the marked position and direction.', 'Places instructions in an executable order.', 'Checks the result by carrying out each instruction.', 'Changes the sequence rather than blaming the toy when the route fails.'],
    sampleAttempt: 'I put forward, turn right, forward. The toy went to the side goal when I followed each card.',
    humanReview: 'Met for this supported physical sequence. Independent planning, symbol reading, debugging language, device use, and broader computing understanding were not established.',
    nextEvidence: 'Introduce one route that fails, invite a single-card change, and observe whether the learner can explain what the changed instruction does.',
  },
  {
    id: 'geography-fictional-place-pattern',
    subject: 'Geography and environment',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Explain a pattern on a fictional place map',
    sourceBoundary: 'Original fictional map description and counts. It supplies no evidence about a real place and is not a curriculum statement or fieldwork substitute.',
    learningIntention: 'Identify a spatial pattern and connect it to evidence without claiming one certain cause.',
    model: 'Fictional map: six bus stops are marked. Five sit along the two main roads and one sits beside a smaller lane. Supported pattern: most stops are on main roads. Possible explanation: the routes may follow roads connecting more places, but the map alone does not prove why each stop was chosen.',
    checkPrompt: 'Describe the bus-stop pattern, cite two map details, and state one possible explanation plus one fact still needed.',
    successCriteria: ['Locates the pattern rather than listing every symbol.', 'Uses at least two details from the fictional map.', 'Labels the explanation as possible and names missing evidence.'],
    sampleAttempt: 'Five of six stops are on the main roads, so most follow those routes. This may help buses connect busy places, but we would need route or passenger information to test that.',
    humanReview: 'Met for pattern, evidence and bounded explanation in this synthetic map. Real map reading, scale use, field observation and curriculum alignment were not established.',
    nextEvidence: 'Change the map scale or add population data and inspect whether the learner preserves, revises or rejects the first explanation.',
  },
  {
    id: 'art-paper-bridge-iteration',
    subject: 'Art and design',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Use a trial to revise a paper structure',
    sourceBoundary: 'Original low-risk paper-design scenario. Material safety, accessibility, cultural context and stage suitability require adult review.',
    learningIntention: 'Use evidence from one material trial to explain a purposeful design change.',
    model: 'Trial one uses a flat paper strip between two blocks and bends under three counters. Trial two folds the strip into a shallow concertina before retesting. The fold is a purposeful iteration intended to change stiffness; a fair comparison keeps span, paper and counters consistent.',
    checkPrompt: 'Describe what the first trial showed, make one purposeful change, and explain how the next test will show its effect.',
    successCriteria: ['Records an observable trial result.', 'Links one change to an intended effect.', 'Keeps other stated test conditions consistent.'],
    sampleAttempt: 'The flat strip bent at three counters. I folded the same paper and kept the blocks the same distance apart. I will add counters one at a time to compare when it bends.',
    humanReview: 'Met for evidence-led iteration in this synthetic task. Visual communication, wider material knowledge, originality and independent design practice were not inferred.',
    nextEvidence: 'Offer two different folds and ask the learner to predict, test and explain which structural feature affected the result.',
  },
  {
    id: 'music-pulse-rhythm-rehearsal',
    subject: 'Music and performance',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Keep a pulse while a rhythm changes',
    sourceBoundary: 'Original body-percussion pattern. It is not a curriculum statement, performance assessment or claim about one musical tradition.',
    learningIntention: 'Distinguish a steady pulse from a changing rhythm and use listening to improve one short section.',
    model: 'Tap four steady beats on knees. Over the same four beats, clap once on beats one and two, twice evenly on beat three, and rest on beat four. The knee taps keep the pulse while the claps form a different rhythm.',
    checkPrompt: 'Maintain the four-beat pulse, perform the clap rhythm, then identify the first beat where the two layers stop matching the plan.',
    successCriteria: ['Keeps or identifies the steady underlying beat.', 'Performs or represents the changing rhythm separately.', 'Uses listening or observation to locate one rehearsal point.'],
    sampleAttempt: 'My knee pulse stayed steady for beats one and two. I rushed the two claps on beat three, so I practised that beat alone before joining it back.',
    humanReview: 'Met for this supported pulse-rhythm distinction and local rehearsal. Ensemble independence, notation, pitch, composition and broader musicianship were not established.',
    nextEvidence: 'Change the rhythm while retaining the pulse and inspect whether the learner can represent and rehearse the new relationship.',
  },
  {
    id: 'pe-safe-space-decision',
    subject: 'Physical education',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Notice and use safe space in a passing task',
    sourceBoundary: 'Original low-intensity movement scenario. A responsible adult must review space, equipment, access, health and safeguarding before use.',
    learningIntention: 'Explain how one movement decision creates a safer or more useful passing option.',
    model: 'In a marked walking-only grid, one player moves away from a crowded corner into an open side channel before receiving a soft ball. The useful evidence is the changed distance and clear passing line, not speed or winning.',
    checkPrompt: 'Walk the pattern safely, identify when a passing lane opens, and explain which movement created it.',
    successCriteria: ['Stays inside the agreed safety and movement rules.', 'Identifies an observable open passing line.', 'Connects one position change to the new option.'],
    sampleAttempt: 'I moved sideways into the empty channel. The passer could see a clear line to me because another player was no longer between us.',
    humanReview: 'Met for one spatial decision in this adapted task. Fitness, competition performance, confidence and independent game transfer were not assessed.',
    nextEvidence: 'Move one defender marker and ask the learner to choose, try and explain a different safe route into space.',
  },
  {
    id: 'citizenship-fictional-claim-check',
    subject: 'Citizenship and media literacy',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Check a claim against its fictional source',
    sourceBoundary: 'Entirely fictional notice and comment created for safe source reasoning. It contains no real public issue, person, organisation or live link.',
    learningIntention: 'Separate a claim from its source evidence and state what remains unknown.',
    model: 'Fictional council notice: “The library will open one hour later on Tuesday during building work.” Fictional comment: “The library is closing.” The notice supports a temporary Tuesday-hours change, not permanent closure. It does not prove whether later dates will change.',
    checkPrompt: 'State what the notice supports, what the comment adds, and one fact that must be checked before sharing a conclusion.',
    successCriteria: ['Distinguishes the two fictional sources.', 'Keeps the supported claim within the notice wording.', 'Names missing context or evidence.'],
    sampleAttempt: 'The notice says Tuesday starts one hour later during work. The comment calls that closing, which is wider than the notice. I would check the dates and current official timetable before sharing.',
    humanReview: 'Met for this synthetic claim-source distinction. Live-source evaluation, civic knowledge, personal views and safe independent searching were not assessed.',
    nextEvidence: 'Add a dated fictional update and inspect whether the learner revises the conclusion while preserving the source timeline.',
  },
  {
    id: 'wellbeing-fictional-help-route',
    subject: 'Health and wellbeing',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Choose a safe help route in a fictional scenario',
    sourceBoundary: 'Original fictional safeguarding scenario for supervised discussion. It is not counselling, diagnosis, emergency handling or an invitation for disclosure.',
    learningIntention: 'Name a safe action, privacy boundary and trusted-adult route for a fictional digital-pressure scenario.',
    model: 'Scenario: a game message asks a fictional child to keep a secret and send a private photo. Safe response: do not send it, stop replying, keep available evidence without resharing it, and tell a trusted adult. Immediate danger requires the setting’s emergency procedure.',
    checkPrompt: 'Choose the first safe action, state what should remain private, and name who should help next.',
    successCriteria: ['Refuses the unsafe request.', 'Protects private information.', 'Names an appropriate trusted adult or emergency route without requesting personal disclosure.'],
    sampleAttempt: 'Do not send the photo or keep chatting. Show the message to a trusted adult. Do not post it publicly because that spreads private information.',
    humanReview: 'Met for the fictional safety route. No inference was made about the learner’s experience, wellbeing, home support or ability to act alone.',
    nextEvidence: 'Use a second fictional scenario with a less obvious pressure tactic and check whether the same safety principles transfer.',
  },
  {
    id: 'money-fictional-total-cost',
    subject: 'Money and life skills',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Compare fictional options using total cost',
    sourceBoundary: 'Original fictional prices for arithmetic practice. This is not financial advice, a real offer or evidence about any learner household.',
    learningIntention: 'Calculate and compare total stated costs over the same period.',
    model: 'Fictional club A costs 6 pounds each month for four months: 24 pounds total. Club B costs 20 pounds once plus a 2-pound materials fee: 22 pounds total. B has the lower stated total, but other features would need named evidence.',
    checkPrompt: 'Calculate both totals, show the operations, and explain one cost and one non-cost fact needed for a fair decision.',
    successCriteria: ['Uses the same four-month period.', 'Includes every stated fee.', 'Shows accurate operations and keeps an unstated preference separate.'],
    sampleAttempt: 'A is 6 x 4 = 24 pounds. B is 20 + 2 = 22 pounds. B costs 2 pounds less, but I would also need to know the times and what activities are included.',
    humanReview: 'Met for the fictional total-cost comparison. Personal budgeting, affordability, value judgement and independent financial decision-making were not inferred.',
    nextEvidence: 'Add a repeat fee or changed time period and inspect whether the learner rebuilds the comparison using common units.',
  },
  {
    id: 'belief-fictional-account-scope',
    subject: 'Religion, belief and philosophy',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Keep a worldview claim within its source',
    sourceBoundary: 'Two fictional community statements created to model source scope. They describe no real religion, worldview, person or community.',
    learningIntention: 'Compare reasons in two accounts without treating either fictional speaker as representative of everyone.',
    model: 'Fictional speaker A joins a shared meal because it expresses duty to neighbours. Fictional speaker B joins because shared action builds belonging without a religious reason. Both support community participation, but their reasons differ and neither account represents every worldview.',
    checkPrompt: 'State one similarity, one difference in reasons, and one claim these two accounts cannot support.',
    successCriteria: ['Represents both fictional accounts accurately.', 'Distinguishes action from reason.', 'Refuses to generalise beyond the two sources.'],
    sampleAttempt: 'Both speakers join the meal and value community. A gives a duty-based reason and B gives a belonging reason. We cannot say everyone in either worldview thinks the same.',
    humanReview: 'Met for bounded comparison in the fictional accounts. Knowledge of real traditions, personal belief, ethical evaluation and wider source interpretation were not assessed.',
    nextEvidence: 'Add contextual information or a third fictional account and ask how it qualifies the first comparison without demanding personal belief.',
  },
] as const;

export type WorkedExample = typeof workedExamples[number];
export type WorkedExampleId = WorkedExample['id'];
