export const workedExamples = [
  {
    id: 'english-claim-evidence',
    subject: 'English',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Separate a claim from its evidence',
    sourceBoundary: 'Synthetic paragraph authored for this demonstration. It is not curriculum evidence and must be replaced by reviewed stage-specific evidence.',
    learningIntention: 'Identify a claim and explain how one detail supports it.',
    model: 'Paragraph: “The path was difficult to use. Rain had filled its deepest cracks, and two loose stones moved under every step.” Claim: the path was difficult to use. Evidence: the filled cracks and moving stones. The details support the claim because they describe obstacles and unstable footing.',
    checkPrompt: 'State the claim. Quote or describe one supporting detail. Explain the connection in one sentence.',
    successCriteria: ['Names the claim rather than retelling the whole paragraph.', 'Selects a relevant detail.', 'Explains why the detail supports the claim.'],
    sampleAttempt: 'The claim is that the path was difficult. The stones moved. This could make someone lose balance, so it supports the claim.',
    humanReview: 'Met for this attempt: claim, relevant detail, and connection are all visible. This does not establish broad reading attainment.',
    nextEvidence: 'Use a second paragraph where evidence is less physically obvious and inspect whether the same distinction transfers.',
  },
  {
    id: 'mathematics-equivalent-fractions',
    subject: 'Mathematics',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Explain equivalent fractions with structure',
    sourceBoundary: 'Original worked example. It is not a programme-of-study statement or proof of stage suitability.',
    learningIntention: 'Explain why 3/4 and 6/8 name the same proportion.',
    model: 'Split one same-sized rectangle into 4 equal parts and shade 3. Split an identical rectangle into 8 equal parts by halving every quarter; 6 eighths are shaded. Both numerator and denominator doubled, while the shaded proportion stayed unchanged.',
    checkPrompt: 'Show whether 2/3 and 4/6 are equivalent using a representation and one explanation.',
    successCriteria: ['Uses equal wholes.', 'Represents both fractions accurately.', 'Explains that numerator and denominator changed by the same factor while the proportion stayed equal.'],
    sampleAttempt: 'I divided both same-sized bars into thirds, then split each third in half. Two thirds covered the same length as four sixths, so they are equivalent.',
    humanReview: 'Met for this representation and explanation. No speed, grade, or general fraction mastery is inferred.',
    nextEvidence: 'Test a non-equivalent close case and ask which structural condition fails.',
  },
  {
    id: 'science-observation-inference',
    subject: 'Science',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Distinguish observation from inference',
    sourceBoundary: 'Original safe desk-based scenario. It is not an authorization for unsupervised practical work or a curriculum statement.',
    learningIntention: 'Separate what was observed from an explanation inferred from it.',
    model: 'Scenario: droplets appear on the outside of a sealed cup containing cold water. Observation: visible droplets formed on the outside surface. Inference: water vapour in the surrounding air may have condensed on the cold surface. The inference uses a model; it was not seen directly.',
    checkPrompt: 'Write one observation and one inference from the scenario. Label each and explain the difference.',
    successCriteria: ['Observation describes directly available evidence.', 'Inference offers a plausible explanation.', 'The response does not present the explanation as something directly seen.'],
    sampleAttempt: 'Observation: drops appeared outside the cup. Inference: water in the air changed to liquid on the cold cup. I could see the drops but not the change happening molecule by molecule.',
    humanReview: 'Met for the distinction in this scenario. Accuracy and stage-specific model language still require subject review.',
    nextEvidence: 'Provide a second observation with two plausible explanations and ask what additional evidence would discriminate between them.',
  },
  {
    id: 'history-source-provenance',
    subject: 'History and histories',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Ask what a source can support',
    sourceBoundary: 'Entirely fictional meeting-note extract created for workflow demonstration. It supplies no evidence about a real past event.',
    learningIntention: 'Use provenance to bound a historical claim.',
    model: 'Fictional extract: “Meeting note, Northbridge Works committee, 14 March 1890: the new bell will begin the morning shift ten minutes earlier.” Direct support: the committee recorded an intended timetable change. It does not by itself prove workers agreed, the change happened, or how every worker experienced it.',
    checkPrompt: 'State one claim the fictional note could support and one claim it could not support alone. Explain why.',
    successCriteria: ['Uses the source creator, date, form, or purpose.', 'Keeps the supported claim close to the extract.', 'Names missing evidence for the unsupported claim.'],
    sampleAttempt: 'It supports that the committee intended an earlier start. It cannot prove workers accepted it because no worker response is included.',
    humanReview: 'Met for this fictional source-evaluation task. It is not evidence of knowledge about a real period or event.',
    nextEvidence: 'Add a conflicting fictional worker letter and inspect how the account changes without treating either source as complete truth.',
  },
  {
    id: 'languages-greeting-exchange',
    subject: 'Languages',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Use a greeting and name exchange for meaning',
    sourceBoundary: 'Original French micro-example for demonstrating the workflow. Register, pronunciation, cultural context, and stage suitability require a qualified human review.',
    learningIntention: 'Understand and produce a short informal greeting and name exchange.',
    model: 'Speaker A: “Bonjour. Je m’appelle Maya. Comment tu t’appelles ?” Speaker B: “Bonjour. Je m’appelle Sam.” Notice the greeting, name statement, and return question. The informal “tu” form is a contextual choice, not a universal default.',
    checkPrompt: 'Complete a two-person informal greeting and name exchange, then identify the greeting and question.',
    successCriteria: ['Meaning is intelligible.', 'A greeting and name statement are present.', 'The response includes or recognizes the return question.', 'Register remains appropriate to the stated informal scenario.'],
    sampleAttempt: 'Bonjour. Je m’appelle Sam. Comment tu t’appelles ?',
    humanReview: 'Partially met in isolation: the required language is present, but listening, pronunciation, response to a partner, and independent transfer were not observed.',
    nextEvidence: 'Use a short spoken exchange with a different name and inspect comprehension before written recall.',
  },
  {
    id: 'computing-trace-state',
    subject: 'Computing and IT',
    stage: 'ks3',
    stageLabel: 'Key Stage 3 lens',
    title: 'Trace program state before changing code',
    sourceBoundary: 'Original language-neutral pseudocode. It is not tied to a qualification, programming language, or configured curriculum statement.',
    learningIntention: 'Trace how a variable changes through a simple loop.',
    model: 'Pseudocode: total = 0; for each n in [2, 3, 4], set total = total + n. Trace: start 0; after 2 → 2; after 3 → 5; after 4 → 9. The final value follows from each state change, not a guess from the list.',
    checkPrompt: 'Trace total for [1, 4, 2] and record its value after every iteration.',
    successCriteria: ['Starts from the initialized value.', 'Processes items in order.', 'Records each intermediate state.', 'Final result matches the trace.'],
    sampleAttempt: 'Start 0; after 1 it is 1; after 4 it is 5; after 2 it is 7. Final total 7.',
    humanReview: 'Met for this loop trace. It does not establish ability to write loops, debug another program, or explain iteration generally.',
    nextEvidence: 'Change the update expression or initial value and ask the learner to predict, trace, and explain the changed result.',
  },
  {
    id: 'english-sequence-retell',
    subject: 'English',
    stage: 'ks1',
    stageLabel: 'Key Stage 1 lens',
    title: 'Sequence a short event without inventing detail',
    sourceBoundary: 'Original three-sentence micro-story. The KS1 label is a planning lens, not reviewed curriculum alignment or proof of reading suitability.',
    learningIntention: 'Put three stated events in order and retell them using sequence words.',
    model: 'Micro-story: “Ari found a seed. Ari pressed it into damp soil. Later, a green shoot appeared.” Model retell: First Ari found a seed. Next Ari planted it in damp soil. Later a green shoot appeared. The retell keeps the stated order and does not add an unstated cause or timescale.',
    checkPrompt: 'Order three event cards from the story, then retell them using first, next, and later.',
    successCriteria: ['Places all three stated events in story order.', 'Uses sequence language to connect the events.', 'Does not add an event that the short text did not state.'],
    sampleAttempt: 'First Ari found the seed. Next Ari put it in the soil. Later the green shoot came up.',
    humanReview: 'Met for sequencing and bounded retell in this synthetic text. Decoding, oral-language independence, writing fluency, and transfer were not established.',
    nextEvidence: 'Use a second short sequence with one distracting illustration detail and inspect whether text order remains the basis of the retell.',
  },
  {
    id: 'mathematics-linear-change',
    subject: 'Mathematics',
    stage: 'ks4',
    stageLabel: 'Key Stage 4 lens',
    title: 'Compare a linear rule with its table',
    sourceBoundary: 'Original algebra example. The KS4 label does not establish qualification coverage, exam-board wording, accessibility, or reviewed curriculum alignment.',
    learningIntention: 'Connect the rule y = 3x - 2 to corresponding values and explain the constant rate of change.',
    model: 'For x values 0, 1, 2, and 3, the rule gives y values -2, 1, 4, and 7. Each increase of 1 in x increases y by 3. The value -2 when x = 0 is the intercept; it is not the step size.',
    checkPrompt: 'Complete a table for y = 4x + 1 at x = -1, 0, 1, and 2. Identify the step change and intercept, then verify one row by substitution.',
    successCriteria: ['Substitutes each x value accurately.', 'Distinguishes the coefficient step change from the intercept.', 'Shows one explicit substitution that reproduces its table value.'],
    sampleAttempt: 'The y values are -3, 1, 5, 9. They go up by 4 each time and the intercept is 1. For x = 2, 4(2) + 1 = 9.',
    humanReview: 'Met for this rule, table, and substitution. Graph interpretation, rearrangement, non-linear comparison, and qualification performance remain untested.',
    nextEvidence: 'Present a table with one erroneous row and ask for evidence identifying whether the rule, substitution, or arithmetic caused the mismatch.',
  },
  {
    id: 'science-material-sort',
    subject: 'Science',
    stage: 'ks1',
    stageLabel: 'Key Stage 1 lens',
    title: 'Sort objects by one observable property',
    sourceBoundary: 'Original desk-based sorting scenario using ordinary classroom objects. The KS1 label is a planning lens and does not replace safety, curriculum, or age-suitability review.',
    learningIntention: 'Group objects using one named observable property and describe the rule used.',
    model: 'Objects: clear plastic ruler, wooden block, metal spoon, clear glass jar. Sort rule: lets light through / does not let light through. The ruler and jar may be grouped as letting light through; the block and spoon do not. Material name and transparency are different descriptions.',
    checkPrompt: 'Sort four supplied safe objects by one visible or touch-observable property. Name the rule and explain where each object belongs.',
    successCriteria: ['Names one observable property before or after sorting.', 'Applies the same rule to every object.', 'Describes observations without claiming an unseen material property.'],
    sampleAttempt: 'I sorted them into bendy and not bendy. The foam and rubber strip bent, but the wooden cube and metal spoon did not bend when I gently tried them.',
    humanReview: 'Met for a consistent observed sorting rule in the stated safe interaction. Material classification, vocabulary breadth, and independent investigation planning were not established.',
    nextEvidence: 'Ask for a different valid sorting rule on the same objects and compare how changing the property changes group membership.',
  },
  {
    id: 'history-change-continuity',
    subject: 'History and histories',
    stage: 'ks2',
    stageLabel: 'Key Stage 2 lens',
    title: 'Separate change from continuity in fictional evidence',
    sourceBoundary: 'Original fictional town records created only for this demonstration. They provide no evidence about a real place, period, or community.',
    learningIntention: 'Identify one change and one continuity between two dated fictional records.',
    model: 'Fictional records: 1840 map note, “Market held beside the bridge each Friday.” 1890 directory, “Friday market now held in the covered hall beside the bridge.” Change: the market moved indoors. Continuity: it remained on Friday and beside the bridge. The records do not explain why the hall was built.',
    checkPrompt: 'State one evidenced change, one evidenced continuity, and one question these two fictional records cannot answer.',
    successCriteria: ['Uses both dates in the comparison.', 'Distinguishes what changed from what remained.', 'Names a missing explanation rather than inventing a cause.'],
    sampleAttempt: 'The market changed from outside to a covered hall. It stayed on Friday near the bridge. The records do not tell us why people moved it indoors.',
    humanReview: 'Met for this bounded comparison. Chronological scale, real contextual knowledge, source reliability, and broader historical explanation were not assessed.',
    nextEvidence: 'Add a third fictional source with a competing description and inspect whether the learner revises the account without discarding earlier evidence.',
  },
  {
    id: 'languages-formal-request',
    subject: 'Languages',
    stage: 'post16-adult',
    stageLabel: 'Post-16 and adult lens',
    title: 'Choose register in a practical French request',
    sourceBoundary: 'Original French service-counter micro-dialogue. The adult label is a dignity and context lens; linguistic accuracy, culture, dialect, pronunciation, and route-specific suitability require qualified review.',
    learningIntention: 'Make and respond to a short polite request using an appropriate formal register.',
    model: 'Customer: “Bonjour, je voudrais un billet pour Lyon, s’il vous plaît.” Staff: “Aller simple ou aller-retour ?” Customer: “Aller-retour, merci.” “Je voudrais” frames a polite request; the exchange still needs listening and clarification skills beyond memorising one sentence.',
    checkPrompt: 'Adapt the exchange to request two return tickets to another destination, then identify the polite request phrase and the clarification question.',
    successCriteria: ['Communicates destination, quantity, and return-ticket meaning.', 'Uses a polite request appropriate to the stated service context.', 'Recognizes and answers the clarification question.'],
    sampleAttempt: 'Bonjour, je voudrais deux billets aller-retour pour Lille, s’il vous plaît. The polite phrase is “je voudrais” and the question asks one-way or return.',
    humanReview: 'Partially met from written evidence: meaning and register are visible, but spoken comprehension, intelligibility, spontaneous repair, and real service interaction were not observed.',
    nextEvidence: 'Use a short audio exchange with a changed destination and one unexpected clarification, then record only the directly observed response evidence.',
  },
  {
    id: 'computing-instruction-sequence',
    subject: 'Computing and IT',
    stage: 'early-learning',
    stageLabel: 'Early-learning reference lens',
    title: 'Sequence instructions for a floor-grid route',
    sourceBoundary: 'Original unplugged activity. EYFS and early-learning curriculum alignment is reference-only; adult supervision, physical access, language demand, and developmental suitability require review.',
    learningIntention: 'Put simple movement instructions in an order that reaches a visible goal.',
    model: 'On a three-square floor path, the toy starts facing forward and the goal is two squares ahead. Model sequence: forward, forward. Run each card in order and stop at the goal. Changing the order changes what happens when turns are included.',
    checkPrompt: 'Choose and order movement cards to move a toy from the marked start to the marked goal, then run the sequence one card at a time.',
    successCriteria: ['Starts from the marked position and direction.', 'Places instructions in an executable order.', 'Checks the result by carrying out each instruction.', 'Changes the sequence rather than blaming the toy when the route fails.'],
    sampleAttempt: 'I put forward, turn right, forward. The toy went to the side goal when I followed each card.',
    humanReview: 'Met for this supported physical sequence. Independent planning, symbol reading, debugging language, device use, and broader computing understanding were not established.',
    nextEvidence: 'Introduce one route that fails, invite a single-card change, and observe whether the learner can explain what the changed instruction does.',
  },
] as const;

export type WorkedExample = typeof workedExamples[number];
export type WorkedExampleId = WorkedExample['id'];
