param([string]$Configuration="Release",[string]$Runtime="win-x64",[string]$LatestOutputPath="",[switch]$SkipNpmRestore)
$ErrorActionPreference="Stop";$repo=Split-Path -Parent $PSScriptRoot;$web=Join-Path $repo "web";$project=Join-Path $repo "ModuleShell\ModuleShell.csproj";$publish=Join-Path $PSScriptRoot "publish";$iss=Join-Path $PSScriptRoot "MA-Teacher.iss";$compiled=Join-Path $PSScriptRoot "bin\MA-Teacher-Setup.exe";$deps=Join-Path $PSScriptRoot "deps";$webViewBootstrapper=Join-Path $deps "MicrosoftEdgeWebview2Setup.exe";$version=[string]((Get-Content (Join-Path $repo "ma-app.json") -Raw|ConvertFrom-Json).version)
$iscc=@($env:ISCC_PATH,"C:\Program Files (x86)\Inno Setup 6\ISCC.exe","C:\Program Files\Inno Setup 6\ISCC.exe")|?{$_-and(Test-Path -LiteralPath $_)}|Select-Object -First 1;if(!$iscc){throw "Inno Setup 6 compiler was not found. Set ISCC_PATH or install Inno Setup 6."}
foreach($required in $project,$iss,(Join-Path $repo "assets\MA-Teacher.ico"),(Join-Path $repo "icon-large.png")){if(!(Test-Path -LiteralPath $required)){throw "Required packaging input is missing: $required"}}
New-Item -ItemType Directory -Force $deps|Out-Null
Invoke-WebRequest -UseBasicParsing -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile $webViewBootstrapper
if(!(Test-Path -LiteralPath $webViewBootstrapper) -or (Get-Item $webViewBootstrapper).Length -lt 100000){throw "WebView2 Evergreen bootstrapper download is missing or invalid"}
Push-Location $web;try{if(!$SkipNpmRestore){& npm.cmd ci;if($LASTEXITCODE){throw "npm restore failed"}};& npm.cmd run build;if($LASTEXITCODE){throw "web build failed"}}finally{Pop-Location}
$indexPath=Join-Path $web "dist\index.html";if(!(Test-Path $indexPath)){throw "Vite index missing"};$index=Get-Content $indexPath -Raw;$refs=[regex]::Matches($index,'(?:src|href)="/?([^"#?]+)"')|%{$_.Groups[1].Value}|?{$_-notmatch'^(?:https?://|data:|mailto:|tel:)'};foreach($ref in $refs){if(!(Test-Path(Join-Path(Join-Path $web "dist")($ref-replace'/','\')))){throw "Missing UI asset: $ref"}}
if(Test-Path $publish){Remove-Item $publish -Recurse -Force};& dotnet publish $project -c $Configuration -r $Runtime --self-contained true -p:PublishSingleFile=false -p:DebugType=None -p:DebugSymbols=false -o $publish;if($LASTEXITCODE){throw "desktop publish failed"}
foreach($required in (Join-Path $publish "MA-Teacher.exe"),(Join-Path $publish "ui\index.html"),(Join-Path $publish "THIRD_PARTY_NOTICES.md")){if(!(Test-Path $required)){throw "Published payload incomplete: $required"}}
& $iscc "/DMyAppVersion=$version" $iss;if($LASTEXITCODE -or !(Test-Path $compiled)){throw "installer compilation failed"};$hash=(Get-FileHash $compiled -Algorithm SHA256).Hash
if($LatestOutputPath){$parent=Split-Path -Parent $LatestOutputPath;if($parent){New-Item -ItemType Directory -Force $parent|Out-Null};Copy-Item $compiled $LatestOutputPath -Force;if((Get-FileHash $LatestOutputPath -Algorithm SHA256).Hash-ne$hash){throw "latest copy hash mismatch"}}
[pscustomobject]@{product="MA-Teacher";version=$version;installerPath=$compiled;latestOutputPath=if($LatestOutputPath){$LatestOutputPath}else{$null};bytes=(Get-Item $compiled).Length;sha256=$hash}|ConvertTo-Json
